import type { LibraryPatternDef } from "@/lib/social-tool/patterns/types";

export const LIBRARY_PATTERNS: LibraryPatternDef[] = [
  {
    id: "diagonal-lines",
    label: "Diagonal lines",
    category: "lines",
    tileWidth: 10,
    tileHeight: 10,
    tags: ["lines", "stripe"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10"><path d="M-1 1l2-2M0 10L10 0M9 11l2-2" stroke="currentColor" stroke-width="1" fill="none"/></svg>`,
  },
  {
    id: "horizontal-stripes",
    label: "Horizontal stripes",
    category: "lines",
    tileWidth: 8,
    tileHeight: 8,
    tags: ["lines"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" viewBox="0 0 8 8"><path d="M0 0h8v2H0zM0 4h8v2H0z" fill="currentColor"/></svg>`,
  },
  {
    id: "vertical-stripes",
    label: "Vertical stripes",
    category: "lines",
    tileWidth: 8,
    tileHeight: 8,
    tags: ["lines"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" viewBox="0 0 8 8"><path d="M0 0h2v8H0zM4 0h2v8H4z" fill="currentColor"/></svg>`,
  },
  {
    id: "polka-small",
    label: "Small dots",
    category: "dots",
    tileWidth: 16,
    tileHeight: 16,
    tags: ["dots"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><circle cx="4" cy="4" r="1.5" fill="currentColor"/><circle cx="12" cy="12" r="1.5" fill="currentColor"/></svg>`,
  },
  {
    id: "polka-large",
    label: "Large dots",
    category: "dots",
    tileWidth: 24,
    tileHeight: 24,
    tags: ["dots"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><circle cx="6" cy="6" r="3" fill="currentColor"/><circle cx="18" cy="18" r="3" fill="currentColor"/></svg>`,
  },
  {
    id: "dots-grid",
    label: "Dot grid",
    category: "dots",
    tileWidth: 20,
    tileHeight: 20,
    tags: ["grid", "dots"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><circle cx="2" cy="2" r="1" fill="currentColor"/><circle cx="10" cy="2" r="1" fill="currentColor"/><circle cx="18" cy="2" r="1" fill="currentColor"/><circle cx="2" cy="10" r="1" fill="currentColor"/><circle cx="10" cy="10" r="1" fill="currentColor"/><circle cx="18" cy="10" r="1" fill="currentColor"/><circle cx="2" cy="18" r="1" fill="currentColor"/><circle cx="10" cy="18" r="1" fill="currentColor"/><circle cx="18" cy="18" r="1" fill="currentColor"/></svg>`,
  },
  {
    id: "triangles",
    label: "Triangles",
    category: "geometric",
    tileWidth: 24,
    tileHeight: 24,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M0 24L12 0 24 24z" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "chevron",
    label: "Chevron",
    category: "geometric",
    tileWidth: 20,
    tileHeight: 20,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path d="M0 10l10-8 10 8-10 8z" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "zigzag",
    label: "Zigzag",
    category: "geometric",
    tileWidth: 16,
    tileHeight: 8,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="8" viewBox="0 0 16 8"><path d="M0 4l4-4 4 4 4-4 4 4" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>`,
  },
  {
    id: "herringbone",
    label: "Herringbone",
    category: "geometric",
    tileWidth: 20,
    tileHeight: 20,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path d="M0 20L10 0 20 20M-10 20L0 0 10 20M10 20L20 0 30 20" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "cross",
    label: "Cross",
    category: "geometric",
    tileWidth: 16,
    tileHeight: 16,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M8 0v16M0 8h16" stroke="currentColor" stroke-width="1" fill="none"/></svg>`,
  },
  {
    id: "plus",
    label: "Plus",
    category: "texture",
    tileWidth: 20,
    tileHeight: 20,
    tags: ["texture"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path d="M10 6v8M6 10h8" stroke="currentColor" stroke-width="2" fill="none"/></svg>`,
  },
  {
    id: "topography",
    label: "Topography",
    category: "organic",
    tileWidth: 100,
    tileHeight: 100,
    tags: ["organic"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><path d="M0 50 Q25 30 50 50 T100 50" fill="none" stroke="currentColor" stroke-width="1"/><path d="M0 70 Q25 50 50 70 T100 70" fill="none" stroke="currentColor" stroke-width="1"/><path d="M0 30 Q25 10 50 30 T100 30" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "moroccan",
    label: "Moroccan",
    category: "organic",
    tileWidth: 40,
    tileHeight: 40,
    tags: ["organic"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40"><path d="M20 0c11 0 20 9 20 20s-9 20-20 20S0 31 0 20 9 0 20 0zm0 8c-6.6 0-12 5.4-12 12s5.4 12 12 12 12-5.4 12-12S26.6 8 20 8z" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "circuit",
    label: "Circuit",
    category: "organic",
    tileWidth: 32,
    tileHeight: 32,
    tags: ["tech"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M0 16h8M24 16h8M16 0v8M16 24v8M8 8h16v16H8z" fill="none" stroke="currentColor" stroke-width="1"/><circle cx="16" cy="16" r="2" fill="currentColor"/></svg>`,
  },
  {
    id: "waves",
    label: "Waves",
    category: "texture",
    tileWidth: 40,
    tileHeight: 20,
    tags: ["waves"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="20" viewBox="0 0 40 20"><path d="M0 10c5-5 10-5 15 0s10 5 15 0 10-5 10 0" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>`,
  },
  {
    id: "bubbles",
    label: "Bubbles",
    category: "texture",
    tileWidth: 48,
    tileHeight: 48,
    tags: ["organic"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><circle cx="12" cy="12" r="8" fill="none" stroke="currentColor" stroke-width="1"/><circle cx="36" cy="36" r="10" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "grid",
    label: "Grid",
    category: "geometric",
    tileWidth: 20,
    tileHeight: 20,
    tags: ["grid"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path d="M20 0v20H0" fill="none" stroke="currentColor" stroke-width="0.5"/></svg>`,
  },
  {
    id: "hexagons",
    label: "Hexagons",
    category: "geometric",
    tileWidth: 28,
    tileHeight: 24,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="24" viewBox="0 0 28 24"><path d="M7 0l7 4v8l-7 4-7-4V4zM21 8l7 4v8l-7 4-7-4v-8z" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "diamonds",
    label: "Diamonds",
    category: "geometric",
    tileWidth: 16,
    tileHeight: 16,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M8 0l8 8-8 8L0 8z" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "confetti",
    label: "Confetti",
    category: "texture",
    tileWidth: 32,
    tileHeight: 32,
    tags: ["texture"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><rect x="4" y="4" width="4" height="8" rx="1" fill="currentColor" transform="rotate(15 6 8)"/><rect x="20" y="12" width="3" height="6" rx="1" fill="currentColor" transform="rotate(-20 21 15)"/><rect x="10" y="22" width="5" height="3" rx="1" fill="currentColor" transform="rotate(35 12 23)"/></svg>`,
  },
  {
    id: "slash",
    label: "Slash",
    category: "lines",
    tileWidth: 12,
    tileHeight: 12,
    tags: ["lines"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12"><path d="M0 12L12 0" stroke="currentColor" stroke-width="2" fill="none"/></svg>`,
  },
  {
    id: "squares",
    label: "Squares",
    category: "geometric",
    tileWidth: 24,
    tileHeight: 24,
    tags: ["geometric"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><rect x="2" y="2" width="8" height="8" fill="none" stroke="currentColor" stroke-width="1"/><rect x="14" y="14" width="8" height="8" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
  {
    id: "arcs",
    label: "Arcs",
    category: "organic",
    tileWidth: 40,
    tileHeight: 40,
    tags: ["organic"],
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40"><path d="M0 40a40 40 0 0 1 40-40" fill="none" stroke="currentColor" stroke-width="1"/><path d="M0 20a20 20 0 0 1 20-20" fill="none" stroke="currentColor" stroke-width="1"/></svg>`,
  },
];

const libraryById = new Map(LIBRARY_PATTERNS.map((p) => [p.id, p]));

export function getLibraryPattern(id: string): LibraryPatternDef | undefined {
  return libraryById.get(id);
}

export function libraryPatternRef(id: string): string {
  return `library:${id}`;
}
