import type { LucideIcon } from "lucide-react";
import {
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart3,
  Briefcase,
  Building2,
  ChevronRight,
  CircleCheck,
  CirclePlus,
  Globe,
  Hash,
  Heart,
  Lightbulb,
  Link,
  Mail,
  Megaphone,
  MessageCircle,
  MoveRight,
  Phone,
  Quote,
  Rocket,
  Share2,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserRound,
  Users,
  Zap,
} from "lucide-react";

/** Tree-shakeable map of catalog icons — avoids importing the full lucide-react bundle. */
export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart3,
  Briefcase,
  Building2,
  ChevronRight,
  CircleCheck,
  CirclePlus,
  Globe,
  Hash,
  Heart,
  Lightbulb,
  Link,
  Mail,
  Megaphone,
  MessageCircle,
  MoveRight,
  Phone,
  Quote,
  Rocket,
  Share2,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserRound,
  Users,
  Zap,
};

export function resolveLucideIcon(iconName: string): LucideIcon | undefined {
  return LUCIDE_ICON_MAP[iconName];
}
