/* AUTO-GENERATED by scripts/compile-design-config.mjs — do not edit by hand */
/* eslint-disable */
export const designConfigData = {
  "artifacts": [
    {
      "id": "birthday_invite",
      "category": "events",
      "label": "Birthday Invite",
      "capabilities": {
        "multiPage": false,
        "print": true,
        "slides": 1,
        "aspectRatios": [
          "5:7",
          "2:3"
        ],
        "primaryContent": "photo"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "body",
          "cta"
        ],
        "optionalSlots": [
          "photo",
          "contact"
        ],
        "maxSections": 5
      },
      "allowedRecipes": [
        "invitation_hero",
        "invitation_rsvp",
        "event_footer_recipe"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "invite-card",
        "event-footer",
        "centered-announcement"
      ],
      "renderer": "product-shot",
      "campaignType": "event",
      "unsplashHints": "birthday party celebration colorful kids",
      "inferenceKeywords": [
        "birthday",
        "party invite",
        "turning"
      ]
    },
    {
      "id": "business_card",
      "category": "business",
      "label": "Business Card",
      "capabilities": {
        "multiPage": false,
        "print": true,
        "slides": 1,
        "aspectRatios": [
          "3.5:2"
        ],
        "primaryContent": "text"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "contact"
        ],
        "optionalSlots": [
          "logo",
          "body"
        ],
        "maxTextBlocks": 4,
        "maxSections": 4
      },
      "allowedRecipes": [
        "business_executive",
        "business_minimal"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "business-card",
        "contact-footer",
        "logo-footer-bar"
      ],
      "renderer": "print-doc",
      "unsplashHints": null,
      "inferenceKeywords": [
        "business card",
        "contact card"
      ]
    },
    {
      "id": "certificate",
      "category": "business",
      "label": "Certificate",
      "capabilities": {
        "multiPage": false,
        "print": true,
        "slides": 1,
        "aspectRatios": [
          "11:8.5",
          "16:9"
        ],
        "primaryContent": "text"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "body"
        ],
        "optionalSlots": [
          "logo",
          "contact"
        ]
      },
      "allowedRecipes": [
        "business_certificate",
        "narrative_statement"
      ],
      "recommendedLayouts": [
        "copy-only",
        "copy-statement",
        "centered-announcement"
      ],
      "renderer": "print-doc",
      "inferenceKeywords": [
        "certificate",
        "award",
        "completion",
        "achievement"
      ]
    },
    {
      "id": "checklist",
      "category": "education",
      "label": "Checklist",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "2:3",
          "1:1"
        ],
        "primaryContent": "text"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "body"
        ],
        "optionalSlots": [
          "subheading"
        ],
        "maxSections": 10
      },
      "allowedRecipes": [
        "education_framework",
        "narrative_statement"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "section-stack",
        "copy-statement",
        "professional-left"
      ],
      "renderer": "product-shot",
      "inferenceKeywords": [
        "checklist",
        "cheat sheet",
        "tips list",
        "how to"
      ]
    },
    {
      "id": "comparison_chart",
      "category": "education",
      "label": "Comparison Chart",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "16:9",
          "1:1"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "body",
          "metric"
        ],
        "maxSections": 4
      },
      "allowedRecipes": [
        "comparison_switch",
        "education_framework"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "comparison-columns",
        "balanced-split",
        "section-stack"
      ],
      "renderer": "diagram",
      "inferenceKeywords": [
        "comparison",
        "versus",
        "vs",
        "compare",
        "chart"
      ]
    },
    {
      "id": "flowchart",
      "category": "documentation",
      "label": "Flowchart",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "16:9",
          "1:1"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "diagram",
          "body"
        ]
      },
      "allowedRecipes": [
        "documentation_flow",
        "education_framework"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "diagram-primary",
        "deck-sidebar",
        "section-stack"
      ],
      "renderer": "diagram",
      "inferenceKeywords": [
        "flowchart",
        "flow chart",
        "process flow",
        "workflow"
      ]
    },
    {
      "id": "framework",
      "category": "education",
      "label": "Framework",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "1:1",
          "16:9"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "body",
          "diagram",
          "metric"
        ],
        "maxSections": 6
      },
      "allowedRecipes": [
        "education_framework",
        "education_timeline"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "section-stack",
        "diagram-primary",
        "copy-statement"
      ],
      "renderer": "diagram",
      "inferenceKeywords": [
        "framework",
        "model",
        "steps",
        "pillars",
        "methodology"
      ]
    },
    {
      "id": "hiring_post",
      "category": "social",
      "label": "Hiring Post",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "1:1",
          "4:5"
        ],
        "primaryContent": "mixed"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "cta"
        ],
        "optionalSlots": [
          "body",
          "logo",
          "featured"
        ]
      },
      "allowedRecipes": [
        "announcement_hero_layout",
        "announcement_center"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "hiring-post",
        "centered-announcement",
        "classic-hero"
      ],
      "renderer": "product-shot",
      "campaignType": "hiring",
      "unsplashHints": "diverse team office hiring",
      "inferenceKeywords": [
        "hiring",
        "we are hiring",
        "job opening",
        "join our team"
      ]
    },
    {
      "id": "infographic",
      "category": "education",
      "label": "Infographic",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "2:3",
          "9:16",
          "1:1"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "body",
          "metric",
          "diagram"
        ],
        "maxTextBlocks": 8,
        "maxSections": 6
      },
      "allowedRecipes": [
        "education_timeline",
        "education_framework",
        "statistic_hero"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "section-stack",
        "diagram-primary",
        "deck-sidebar"
      ],
      "renderer": "diagram",
      "unsplashHints": null,
      "inferenceKeywords": [
        "infographic",
        "visual guide",
        "data story"
      ]
    },
    {
      "id": "instagram_post",
      "category": "marketing",
      "label": "Instagram Post",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "1:1",
          "4:5"
        ],
        "primaryContent": "mixed"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "logo",
          "featured",
          "cta",
          "subheading"
        ],
        "maxTextBlocks": 4
      },
      "allowedRecipes": [
        "offer_hero",
        "announcement_center",
        "narrative_statement"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "social-ad",
        "visual-first",
        "centered-announcement"
      ],
      "renderer": "product-shot",
      "campaignType": "promotion",
      "unsplashHints": "lifestyle brand social media",
      "inferenceKeywords": [
        "instagram",
        "ig post",
        "social post"
      ]
    },
    {
      "id": "linkedin_ad",
      "category": "marketing",
      "label": "LinkedIn Ad",
      "capabilities": {
        "multiPage": false,
        "print": false,
        "slides": 1,
        "aspectRatios": [
          "1:1",
          "4:5"
        ],
        "primaryContent": "mixed"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "cta"
        ],
        "optionalSlots": [
          "logo",
          "featured",
          "subheading"
        ],
        "maxTextBlocks": 4
      },
      "allowedRecipes": [
        "offer_hero",
        "announcement_hero_layout",
        "statistic_hero",
        "problem_solution_flow",
        "social_proof_strip"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "social-ad",
        "balanced-split",
        "professional-left"
      ],
      "renderer": "product-shot",
      "campaignType": "advertisement",
      "unsplashHints": "professional business office team",
      "inferenceKeywords": [
        "linkedin",
        "b2b",
        "ad",
        "sponsored"
      ]
    },
    {
      "id": "meetup_poster",
      "category": "events",
      "label": "Meetup Poster",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "4:5",
          "2:3",
          "1:1"
        ],
        "primaryContent": "photo"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "subheading",
          "body",
          "contact",
          "cta"
        ],
        "optionalSlots": [
          "logo",
          "photo"
        ],
        "maxTextBlocks": 6,
        "maxSections": 4
      },
      "allowedRecipes": [
        "invitation_hero",
        "announcement_hero_layout",
        "event_footer_recipe"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "event-poster",
        "event-footer",
        "contact-footer"
      ],
      "renderer": "product-shot",
      "campaignType": "event",
      "unsplashHints": "community meetup coffee workshop gathering",
      "inferenceKeywords": [
        "meetup",
        "workshop",
        "gathering",
        "conference poster",
        "community event",
        "design challenge"
      ]
    },
    {
      "id": "org_chart",
      "category": "documentation",
      "label": "Org Chart",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "16:9",
          "1:1"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "diagram",
          "body"
        ]
      },
      "allowedRecipes": [
        "documentation_org",
        "documentation_flow"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "diagram-primary",
        "deck-sidebar",
        "section-stack"
      ],
      "renderer": "diagram",
      "inferenceKeywords": [
        "org chart",
        "organization",
        "team structure",
        "hierarchy"
      ]
    },
    {
      "id": "pitch_deck",
      "category": "presentations",
      "label": "Pitch Deck",
      "capabilities": {
        "multiPage": true,
        "slides": 20,
        "speakerNotes": true,
        "aspectRatios": [
          "16:9"
        ],
        "primaryContent": "mixed"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "body",
          "metric",
          "diagram",
          "featured"
        ],
        "maxSections": 12
      },
      "allowedRecipes": [
        "presentation_title",
        "presentation_agenda",
        "presentation_problem",
        "presentation_solution",
        "presentation_roadmap",
        "presentation_closing"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "deck-sidebar",
        "section-stack",
        "copy-statement"
      ],
      "renderer": "slide-deck",
      "unsplashHints": "startup office presentation",
      "inferenceKeywords": [
        "pitch deck",
        "investor deck",
        "seed round",
        "fundraising"
      ]
    },
    {
      "id": "process_flow",
      "category": "documentation",
      "label": "Process Flow",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "16:9",
          "1:1"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "diagram",
          "body"
        ]
      },
      "allowedRecipes": [
        "documentation_flow",
        "education_framework"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "diagram-primary",
        "deck-sidebar",
        "section-stack"
      ],
      "renderer": "diagram",
      "inferenceKeywords": [
        "process",
        "sop",
        "procedure",
        "steps"
      ]
    },
    {
      "id": "proposal_cover",
      "category": "business",
      "label": "Proposal Cover",
      "capabilities": {
        "multiPage": false,
        "print": true,
        "slides": 1,
        "aspectRatios": [
          "8.5:11",
          "16:9"
        ],
        "primaryContent": "text"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "subheading"
        ],
        "optionalSlots": [
          "logo",
          "body",
          "contact"
        ]
      },
      "allowedRecipes": [
        "announcement_hero_layout",
        "narrative_statement"
      ],
      "recommendedLayouts": [
        "proposal-cover",
        "copy-only",
        "centered-announcement"
      ],
      "renderer": "print-doc",
      "inferenceKeywords": [
        "proposal",
        "cover page",
        "quote",
        "rfp"
      ]
    },
    {
      "id": "quote_card",
      "category": "social",
      "label": "Quote Card",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "1:1",
          "4:5"
        ],
        "primaryContent": "text"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "body",
          "logo"
        ]
      },
      "allowedRecipes": [
        "narrative_statement",
        "announcement_center"
      ],
      "recommendedLayouts": [
        "copy-only",
        "copy-statement",
        "centered-announcement"
      ],
      "renderer": "product-shot",
      "inferenceKeywords": [
        "quote",
        "testimonial",
        "inspiration"
      ]
    },
    {
      "id": "roadmap",
      "category": "presentations",
      "label": "Roadmap",
      "capabilities": {
        "multiPage": true,
        "slides": 10,
        "aspectRatios": [
          "16:9"
        ],
        "primaryContent": "diagram"
      },
      "allowedRecipes": [
        "presentation_roadmap",
        "education_timeline",
        "presentation_title"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "deck-sidebar",
        "section-stack",
        "diagram-primary"
      ],
      "renderer": "slide-deck",
      "inferenceKeywords": [
        "roadmap",
        "quarterly plan",
        "milestones"
      ]
    },
    {
      "id": "rsvp_card",
      "category": "events",
      "label": "RSVP Card",
      "capabilities": {
        "multiPage": false,
        "print": true,
        "slides": 1,
        "aspectRatios": [
          "5:7",
          "3:2"
        ],
        "primaryContent": "text"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "cta",
          "contact"
        ],
        "optionalSlots": [
          "body"
        ]
      },
      "allowedRecipes": [
        "invitation_rsvp",
        "invitation_hero"
      ],
      "recommendedLayouts": [
        "invite-card",
        "event-footer",
        "centered-announcement"
      ],
      "renderer": "product-shot",
      "campaignType": "event",
      "inferenceKeywords": [
        "rsvp",
        "respond",
        "invitation card"
      ]
    },
    {
      "id": "timeline",
      "category": "education",
      "label": "Timeline",
      "capabilities": {
        "multiPage": false,
        "slides": 1,
        "aspectRatios": [
          "16:9",
          "2:3",
          "1:1"
        ],
        "primaryContent": "diagram"
      },
      "constraints": {
        "requiredSlots": [
          "headline"
        ],
        "optionalSlots": [
          "body",
          "diagram"
        ],
        "maxSections": 8
      },
      "allowedRecipes": [
        "education_timeline",
        "education_framework"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "section-stack",
        "diagram-primary",
        "deck-sidebar"
      ],
      "renderer": "diagram",
      "inferenceKeywords": [
        "timeline",
        "chronology",
        "history",
        "roadmap steps"
      ]
    },
    {
      "id": "webinar_slides",
      "category": "presentations",
      "label": "Webinar Slides",
      "capabilities": {
        "multiPage": true,
        "slides": 15,
        "speakerNotes": true,
        "aspectRatios": [
          "16:9"
        ],
        "primaryContent": "mixed"
      },
      "allowedRecipes": [
        "presentation_title",
        "presentation_agenda",
        "presentation_problem",
        "presentation_solution",
        "presentation_closing"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "deck-sidebar",
        "section-stack",
        "copy-statement"
      ],
      "renderer": "slide-deck",
      "campaignType": "webinar",
      "inferenceKeywords": [
        "webinar",
        "slides",
        "presentation"
      ]
    },
    {
      "id": "wedding_invite",
      "category": "events",
      "label": "Wedding Invite",
      "capabilities": {
        "multiPage": false,
        "print": true,
        "slides": 1,
        "aspectRatios": [
          "5:7",
          "2:3"
        ],
        "primaryContent": "photo"
      },
      "constraints": {
        "requiredSlots": [
          "headline",
          "body",
          "cta"
        ],
        "optionalSlots": [
          "photo",
          "contact"
        ]
      },
      "allowedRecipes": [
        "invitation_hero",
        "invitation_rsvp"
      ],
      "recommendedBundles": [],
      "recommendedLayouts": [
        "invite-card",
        "event-footer",
        "centered-announcement"
      ],
      "renderer": "product-shot",
      "campaignType": "event",
      "unsplashHints": "wedding elegant flowers couple",
      "inferenceKeywords": [
        "wedding",
        "save the date",
        "ceremony"
      ]
    }
  ],
  "campaigns": [
    {
      "campaign": "advertisement",
      "label": "Advertisement",
      "designSystem": "offer",
      "headline": {
        "maxWords": 8,
        "emphasis": "offer"
      },
      "subheading": {
        "optional": false,
        "maxWords": 15
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 35
      },
      "spacing": "compact",
      "patterns": [
        "grid",
        "dots"
      ],
      "requiredSlots": [
        "headline",
        "subheading",
        "cta",
        "product_image"
      ],
      "bannedSlots": [
        "body"
      ],
      "defaultPattern": "offer",
      "defaultRecipes": [
        "offer_hero",
        "discount_focus"
      ]
    },
    {
      "campaign": "announcement",
      "label": "Announcement",
      "designSystem": "default",
      "headline": {
        "maxWords": 10,
        "emphasis": "message"
      },
      "subheading": {
        "optional": true,
        "maxWords": 18
      },
      "image": {
        "optional": true
      },
      "cta": {
        "optional": true
      },
      "badge": {
        "optional": true
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 50
      },
      "spacing": "relaxed",
      "patterns": [
        "grid",
        "monogram"
      ],
      "requiredSlots": [
        "headline"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center",
        "announcement_hero_layout"
      ]
    },
    {
      "campaign": "case_study",
      "label": "Case Study",
      "designSystem": "enterprise_saas",
      "headline": {
        "maxWords": 10,
        "emphasis": "outcome"
      },
      "customerLogo": {
        "required": true
      },
      "quote": {
        "required": true
      },
      "metric": {
        "required": true
      },
      "cta": {
        "required": true,
        "type": "learn_more"
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 55
      },
      "spacing": "relaxed",
      "patterns": [
        "grid"
      ],
      "requiredSlots": [
        "headline",
        "quote",
        "metric",
        "customer_logo",
        "cta"
      ],
      "defaultPattern": "social_proof",
      "defaultRecipes": [
        "social_proof_strip",
        "statistic_hero"
      ]
    },
    {
      "campaign": "event",
      "label": "Event",
      "designSystem": "default",
      "headline": {
        "maxWords": 10,
        "emphasis": "event"
      },
      "cta": {
        "required": true,
        "type": "register"
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 45
      },
      "spacing": "default",
      "patterns": [
        "grid"
      ],
      "requiredSlots": [
        "headline",
        "cta"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center",
        "event_footer_recipe"
      ]
    },
    {
      "campaign": "feature_release",
      "label": "Feature Release",
      "designSystem": "enterprise_saas",
      "headline": {
        "maxWords": 8,
        "emphasis": "feature"
      },
      "subheading": {
        "optional": true,
        "maxWords": 16
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 40
      },
      "spacing": "default",
      "patterns": [
        "grid",
        "topography"
      ],
      "requiredSlots": [
        "headline",
        "product_image",
        "cta"
      ],
      "defaultPattern": "problem_solution",
      "defaultRecipes": [
        "problem_solution_flow",
        "offer_hero"
      ]
    },
    {
      "campaign": "hiring",
      "label": "Hiring",
      "designSystem": "default",
      "headline": {
        "maxWords": 8,
        "emphasis": "role"
      },
      "cta": {
        "required": true,
        "type": "apply"
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 45
      },
      "spacing": "default",
      "patterns": [
        "dots"
      ],
      "requiredSlots": [
        "headline",
        "cta"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center"
      ]
    },
    {
      "campaign": "product_launch",
      "label": "Product Launch",
      "designSystem": "enterprise_saas",
      "headline": {
        "maxWords": 8,
        "emphasis": "product"
      },
      "subheading": {
        "optional": true,
        "maxWords": 16
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 40
      },
      "spacing": "default",
      "patterns": [
        "grid",
        "topography"
      ],
      "requiredSlots": [
        "headline",
        "product_image",
        "cta"
      ],
      "defaultPattern": "comparison",
      "defaultRecipes": [
        "comparison_switch",
        "offer_hero",
        "problem_solution_flow"
      ]
    },
    {
      "campaign": "promotion",
      "label": "Promotion",
      "designSystem": "offer",
      "headline": {
        "maxWords": 6,
        "emphasis": "offer"
      },
      "subheading": {
        "optional": true,
        "maxWords": 12
      },
      "offerBadge": {
        "required": true
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 35
      },
      "spacing": "compact",
      "patterns": [
        "gradient_blob",
        "dots",
        "mesh"
      ],
      "requiredSlots": [
        "headline",
        "cta",
        "product_image"
      ],
      "bannedSlots": [
        "body"
      ],
      "defaultPattern": "offer",
      "defaultRecipes": [
        "offer_hero",
        "discount_focus"
      ]
    },
    {
      "campaign": "thought_leadership",
      "label": "Thought Leadership",
      "designSystem": "default",
      "headline": {
        "maxWords": 12,
        "emphasis": "insight"
      },
      "subheading": {
        "optional": true,
        "maxWords": 24
      },
      "cta": {
        "optional": true
      },
      "copy": {
        "density": "high",
        "maxTotalWords": 60
      },
      "spacing": "relaxed",
      "patterns": [
        "monogram"
      ],
      "requiredSlots": [
        "headline"
      ],
      "defaultPattern": "narrative",
      "defaultRecipes": [
        "narrative_statement"
      ]
    },
    {
      "campaign": "webinar",
      "label": "Webinar",
      "designSystem": "default",
      "headline": {
        "maxWords": 10,
        "emphasis": "topic"
      },
      "cta": {
        "required": true,
        "type": "register"
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 45
      },
      "spacing": "default",
      "patterns": [
        "grid"
      ],
      "requiredSlots": [
        "headline",
        "cta",
        "product_image"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center",
        "event_footer_recipe"
      ]
    }
  ],
  "patterns": [
    {
      "id": "announcement_hero",
      "label": "Announcement Hero",
      "description": "Centered message-first announcement.",
      "flow": [
        "Message",
        "Support",
        "Optional CTA"
      ],
      "recipes": [
        "announcement_center",
        "announcement_hero_layout",
        "event_footer_recipe"
      ],
      "campaigns": [
        "announcement",
        "event",
        "webinar",
        "hiring",
        "product_launch"
      ]
    },
    {
      "id": "comparison",
      "label": "Comparison",
      "description": "Old way versus new way, then switch CTA.",
      "flow": [
        "Old Way",
        "New Way",
        "Switch"
      ],
      "recipes": [
        "comparison_switch"
      ],
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement",
        "promotion"
      ]
    },
    {
      "id": "narrative",
      "label": "Narrative",
      "description": "Copy-led storytelling and thought leadership.",
      "flow": [
        "Insight",
        "Context",
        "Soft CTA"
      ],
      "recipes": [
        "narrative_statement"
      ],
      "campaigns": [
        "thought_leadership",
        "announcement"
      ]
    },
    {
      "id": "offer",
      "label": "Offer",
      "description": "Lead with the offer, create urgency, drive CTA.",
      "flow": [
        "Offer",
        "Urgency",
        "CTA"
      ],
      "recipes": [
        "offer_hero",
        "discount_focus"
      ],
      "campaigns": [
        "promotion",
        "advertisement",
        "product_launch"
      ]
    },
    {
      "id": "problem_solution",
      "label": "Problem to Solution",
      "description": "Surface pain, present the solution, drive action.",
      "flow": [
        "Pain",
        "Solution",
        "Action"
      ],
      "recipes": [
        "problem_solution_flow"
      ],
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement"
      ]
    },
    {
      "id": "social_proof",
      "label": "Social Proof",
      "description": "Trust signals via logos, quotes, and outcomes.",
      "flow": [
        "Trusted By",
        "Customer Logos",
        "CTA"
      ],
      "recipes": [
        "social_proof_strip"
      ],
      "campaigns": [
        "case_study",
        "product_launch",
        "advertisement"
      ]
    },
    {
      "id": "statistic",
      "label": "Statistic",
      "description": "Lead with a bold metric, explain, then CTA.",
      "flow": [
        "Metric",
        "Explanation",
        "CTA"
      ],
      "recipes": [
        "statistic_hero"
      ],
      "campaigns": [
        "case_study",
        "thought_leadership",
        "product_launch"
      ]
    }
  ],
  "recipes": [
    {
      "id": "announcement_center",
      "name": "Announcement Center",
      "pattern": "announcement_hero",
      "slots": [
        "logo",
        "badge",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "message",
      "proof": "badge",
      "density": "medium",
      "readingPattern": "center",
      "campaigns": [
        "announcement",
        "hiring",
        "webinar"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "brand-stack",
        "classic-hero"
      ],
      "bundles": [
        "feature-launch"
      ],
      "families": [
        "product",
        "benefits"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "quote_card"
      ]
    },
    {
      "id": "announcement_hero_layout",
      "name": "Announcement Hero Layout",
      "pattern": "announcement_hero",
      "slots": [
        "logo",
        "headline",
        "product_image",
        "cta"
      ],
      "attention": "message",
      "proof": "screenshot",
      "density": "low",
      "readingPattern": "F",
      "campaigns": [
        "announcement",
        "product_launch"
      ],
      "preferredLayouts": [
        "classic-hero",
        "visual-first",
        "product-focus"
      ],
      "bundles": [
        "feature-launch"
      ],
      "families": [
        "product",
        "metric"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "meetup_poster"
      ]
    },
    {
      "id": "business_certificate",
      "name": "Business Certificate",
      "pattern": "announcement_hero",
      "slots": [
        "headline",
        "body",
        "subheading"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "low",
      "readingPattern": "center",
      "artifactSupports": [
        "certificate"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "copy-statement"
      ]
    },
    {
      "id": "business_executive",
      "name": "Business Executive",
      "pattern": "narrative",
      "slots": [
        "headline",
        "body",
        "contact"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "low",
      "readingPattern": "F",
      "artifactSupports": [
        "business_card"
      ],
      "preferredLayouts": [
        "business-card",
        "contact-footer",
        "logo-footer-bar"
      ],
      "families": [
        "product"
      ]
    },
    {
      "id": "business_minimal",
      "name": "Business Minimal",
      "pattern": "narrative",
      "slots": [
        "headline",
        "contact"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "low",
      "readingPattern": "center",
      "artifactSupports": [
        "business_card"
      ],
      "preferredLayouts": [
        "business-card",
        "contact-footer",
        "copy-only"
      ]
    },
    {
      "id": "comparison_switch",
      "name": "Comparison Switch",
      "pattern": "comparison",
      "slots": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "cta"
      ],
      "attention": "new_way",
      "proof": "screenshot",
      "density": "low",
      "readingPattern": "Z",
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement",
        "promotion"
      ],
      "preferredLayouts": [
        "balanced-split",
        "split-feature-right",
        "professional-left",
        "product-focus"
      ],
      "bundles": [
        "growth-proof",
        "feature-launch"
      ],
      "families": [
        "comparison",
        "product"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "comparison_chart",
        "infographic"
      ]
    },
    {
      "id": "discount_focus",
      "name": "Discount Focus",
      "pattern": "offer",
      "slots": [
        "logo",
        "offer_badge",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "offer",
      "proof": "badge",
      "density": "low",
      "readingPattern": "center",
      "campaigns": [
        "promotion",
        "advertisement"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "brand-stack",
        "classic-hero"
      ],
      "bundles": [
        "pricing-offer"
      ],
      "families": [
        "pricing",
        "metric"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post"
      ]
    },
    {
      "id": "documentation_flow",
      "name": "Documentation Flow",
      "pattern": "narrative",
      "slots": [
        "headline",
        "body"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "medium",
      "readingPattern": "F",
      "artifactSupports": [
        "flowchart",
        "process_flow",
        "org_chart"
      ],
      "preferredLayouts": [
        "deck-sidebar",
        "copy-statement"
      ],
      "bundles": [
        "process-explain"
      ],
      "families": [
        "diagram",
        "process"
      ]
    },
    {
      "id": "documentation_org",
      "name": "Documentation Org Chart",
      "pattern": "narrative",
      "slots": [
        "headline",
        "body"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "medium",
      "readingPattern": "center",
      "artifactSupports": [
        "org_chart",
        "flowchart"
      ],
      "preferredLayouts": [
        "deck-sidebar",
        "centered-announcement"
      ],
      "families": [
        "diagram"
      ]
    },
    {
      "id": "education_framework",
      "name": "Education Framework",
      "pattern": "narrative",
      "slots": [
        "headline",
        "subheading",
        "body"
      ],
      "attention": "headline",
      "proof": "stat",
      "density": "medium",
      "readingPattern": "center",
      "artifactSupports": [
        "infographic",
        "timeline",
        "framework",
        "comparison_chart",
        "checklist",
        "flowchart",
        "process_flow"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "copy-statement"
      ],
      "bundles": [
        "process-explain",
        "growth-proof"
      ],
      "families": [
        "diagram",
        "benefits"
      ]
    },
    {
      "id": "education_timeline",
      "name": "Education Timeline",
      "pattern": "narrative",
      "slots": [
        "headline",
        "body",
        "metric"
      ],
      "attention": "headline",
      "proof": "stat",
      "density": "medium",
      "readingPattern": "F",
      "campaigns": [
        "thought_leadership",
        "announcement"
      ],
      "artifactSupports": [
        "infographic",
        "timeline",
        "framework",
        "roadmap"
      ],
      "preferredLayouts": [
        "copy-statement",
        "deck-sidebar"
      ],
      "bundles": [
        "process-explain"
      ],
      "families": [
        "diagram",
        "process"
      ]
    },
    {
      "id": "event_footer_recipe",
      "name": "Event Footer",
      "pattern": "announcement_hero",
      "slots": [
        "logo",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "event",
      "proof": "none",
      "density": "medium",
      "readingPattern": "F",
      "campaigns": [
        "event",
        "webinar"
      ],
      "preferredLayouts": [
        "event-footer",
        "footer-mark",
        "logo-footer-bar",
        "centered-announcement"
      ],
      "bundles": [
        "process-explain"
      ],
      "families": [
        "process",
        "product"
      ],
      "artifactSupports": [
        "birthday_invite",
        "wedding_invite",
        "meetup_poster",
        "rsvp_card"
      ]
    },
    {
      "id": "invitation_hero",
      "name": "Invitation Hero",
      "pattern": "announcement_hero",
      "slots": [
        "headline",
        "subheading",
        "body",
        "cta"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "medium",
      "readingPattern": "center",
      "campaigns": [
        "event"
      ],
      "artifactSupports": [
        "birthday_invite",
        "wedding_invite",
        "meetup_poster",
        "rsvp_card"
      ],
      "preferredLayouts": [
        "event-poster",
        "event-footer",
        "split-feature-right",
        "classic-hero"
      ],
      "families": [
        "product"
      ]
    },
    {
      "id": "invitation_rsvp",
      "name": "Invitation RSVP",
      "pattern": "announcement_hero",
      "slots": [
        "headline",
        "body",
        "cta"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "low",
      "readingPattern": "center",
      "campaigns": [
        "event"
      ],
      "artifactSupports": [
        "birthday_invite",
        "wedding_invite",
        "rsvp_card"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "event-footer"
      ],
      "families": [
        "product"
      ]
    },
    {
      "id": "narrative_statement",
      "name": "Narrative Statement",
      "pattern": "narrative",
      "slots": [
        "logo",
        "headline",
        "body",
        "caption"
      ],
      "attention": "insight",
      "proof": "none",
      "density": "high",
      "readingPattern": "F",
      "campaigns": [
        "thought_leadership",
        "announcement"
      ],
      "preferredLayouts": [
        "copy-statement",
        "deck-sidebar",
        "professional-left"
      ],
      "bundles": [
        "social-proof"
      ],
      "families": [
        "proof",
        "diagram"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "quote_card",
        "proposal_cover"
      ]
    },
    {
      "id": "offer_hero",
      "name": "Offer Hero",
      "pattern": "offer",
      "slots": [
        "logo",
        "offer_badge",
        "headline",
        "product_image",
        "cta"
      ],
      "attention": "offer",
      "proof": "badge",
      "density": "low",
      "readingPattern": "F",
      "campaigns": [
        "promotion",
        "advertisement",
        "product_launch"
      ],
      "preferredLayouts": [
        "classic-hero",
        "visual-first",
        "product-focus",
        "balanced-split"
      ],
      "bundles": [
        "growth-proof",
        "pricing-offer"
      ],
      "families": [
        "metric",
        "pricing"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post"
      ]
    },
    {
      "id": "presentation_agenda",
      "name": "Presentation Agenda",
      "pattern": "narrative",
      "slots": [
        "headline",
        "body"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "medium",
      "readingPattern": "F",
      "artifactSupports": [
        "pitch_deck",
        "webinar_slides"
      ],
      "preferredLayouts": [
        "deck-sidebar",
        "copy-statement"
      ],
      "bundles": [
        "process-explain"
      ]
    },
    {
      "id": "presentation_closing",
      "name": "Presentation Closing",
      "pattern": "announcement_hero",
      "slots": [
        "headline",
        "cta"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "low",
      "readingPattern": "center",
      "artifactSupports": [
        "pitch_deck",
        "webinar_slides"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "deck-sidebar"
      ],
      "families": [
        "product"
      ]
    },
    {
      "id": "presentation_problem",
      "name": "Presentation Problem",
      "pattern": "problem_solution",
      "slots": [
        "headline",
        "subheading",
        "body"
      ],
      "attention": "headline",
      "proof": "stat",
      "density": "medium",
      "readingPattern": "F",
      "artifactSupports": [
        "pitch_deck",
        "webinar_slides"
      ],
      "preferredLayouts": [
        "copy-statement",
        "professional-left"
      ],
      "bundles": [
        "growth-proof"
      ]
    },
    {
      "id": "presentation_roadmap",
      "name": "Presentation Roadmap",
      "pattern": "narrative",
      "slots": [
        "headline",
        "body",
        "metric"
      ],
      "attention": "headline",
      "proof": "stat",
      "density": "medium",
      "readingPattern": "F",
      "artifactSupports": [
        "pitch_deck",
        "roadmap",
        "timeline"
      ],
      "preferredLayouts": [
        "deck-sidebar",
        "copy-statement"
      ],
      "bundles": [
        "process-explain"
      ],
      "families": [
        "diagram",
        "process"
      ]
    },
    {
      "id": "presentation_solution",
      "name": "Presentation Solution",
      "pattern": "problem_solution",
      "slots": [
        "headline",
        "subheading",
        "body",
        "metric"
      ],
      "attention": "headline",
      "proof": "stat",
      "density": "medium",
      "readingPattern": "F",
      "artifactSupports": [
        "pitch_deck",
        "webinar_slides"
      ],
      "preferredLayouts": [
        "balanced-split",
        "deck-sidebar"
      ],
      "bundles": [
        "feature-launch",
        "growth-proof"
      ]
    },
    {
      "id": "presentation_title",
      "name": "Presentation Title",
      "pattern": "announcement_hero",
      "slots": [
        "headline",
        "subheading"
      ],
      "attention": "headline",
      "proof": "none",
      "density": "low",
      "readingPattern": "center",
      "artifactSupports": [
        "pitch_deck",
        "webinar_slides",
        "roadmap"
      ],
      "preferredLayouts": [
        "deck-sidebar",
        "centered-announcement"
      ],
      "bundles": [
        "feature-launch"
      ]
    },
    {
      "id": "problem_solution_flow",
      "name": "Problem Solution Flow",
      "pattern": "problem_solution",
      "slots": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "cta"
      ],
      "attention": "solution",
      "proof": "screenshot",
      "density": "low",
      "readingPattern": "Z",
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement"
      ],
      "preferredLayouts": [
        "balanced-split",
        "split-feature-right",
        "split-feature-left",
        "product-focus"
      ],
      "bundles": [
        "feature-launch",
        "process-explain"
      ],
      "families": [
        "product",
        "benefits",
        "process"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "infographic"
      ]
    },
    {
      "id": "social_proof_strip",
      "name": "Social Proof Strip",
      "pattern": "social_proof",
      "slots": [
        "logo",
        "headline",
        "customer_logo",
        "quote",
        "cta"
      ],
      "attention": "trust",
      "proof": "logos",
      "density": "medium",
      "readingPattern": "F",
      "campaigns": [
        "case_study",
        "product_launch"
      ],
      "preferredLayouts": [
        "professional-left",
        "logo-footer-bar",
        "brand-stack",
        "deck-sidebar"
      ],
      "bundles": [
        "social-proof"
      ],
      "families": [
        "proof",
        "metric"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "hiring_post"
      ]
    },
    {
      "id": "statistic_hero",
      "name": "Statistic Hero",
      "pattern": "statistic",
      "slots": [
        "logo",
        "metric",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "metric",
      "proof": "stat",
      "density": "low",
      "readingPattern": "center",
      "campaigns": [
        "case_study",
        "thought_leadership",
        "product_launch"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "copy-statement",
        "professional-left"
      ],
      "bundles": [
        "growth-proof",
        "social-proof"
      ],
      "families": [
        "metric",
        "proof"
      ],
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "infographic"
      ]
    }
  ],
  "layouts": [
    {
      "id": "balanced-split",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "advertisement",
        "product_launch",
        "promotion",
        "feature_release",
        "case_study"
      ],
      "recipes": [
        "comparison_switch",
        "problem_solution_flow",
        "offer_hero"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "offer_badge",
        "metric"
      ],
      "score": {
        "promotion": 0.82,
        "announcement": 0.68,
        "product_launch": 0.85,
        "advertisement": 0.88,
        "thought_leadership": 0.55,
        "event": 0.5,
        "case_study": 0.75,
        "feature_release": 0.8,
        "webinar": 0.52,
        "hiring": 0.48
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "comparison_chart",
        "infographic"
      ]
    },
    {
      "id": "brand-stack",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "promotion"
      ],
      "recipes": [
        "discount_focus",
        "announcement_center",
        "social_proof_strip"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "offer_badge",
        "customer_logo"
      ],
      "score": {
        "promotion": 0.88,
        "announcement": 0.9,
        "product_launch": 0.65,
        "advertisement": 0.72,
        "thought_leadership": 0.55,
        "event": 0.5,
        "case_study": 0.58,
        "feature_release": 0.6,
        "webinar": 0.48,
        "hiring": 0.62
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "quote_card"
      ]
    },
    {
      "id": "business-card",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "thought_leadership"
      ],
      "visualPriority": "low",
      "contentDensity": "low",
      "readingPattern": "F",
      "visualWeight": "light",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "contact"
      ],
      "score": {
        "announcement": 0.95,
        "thought_leadership": 0.7
      },
      "artifactSupports": [
        "business_card"
      ]
    },
    {
      "id": "centered-announcement",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "hiring"
      ],
      "recipes": [
        "announcement_center",
        "discount_focus",
        "statistic_hero"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "center",
      "visualWeight": "medium",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "badge",
        "offer_badge",
        "metric"
      ],
      "score": {
        "promotion": 0.7,
        "announcement": 0.95,
        "product_launch": 0.62,
        "advertisement": 0.58,
        "thought_leadership": 0.55,
        "event": 0.5,
        "case_study": 0.45,
        "feature_release": 0.6,
        "webinar": 0.48,
        "hiring": 0.9
      },
      "artifactSupports": [
        "infographic",
        "timeline",
        "framework",
        "checklist",
        "certificate",
        "proposal_cover"
      ]
    },
    {
      "id": "classic-hero",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "product_launch",
        "promotion"
      ],
      "recipes": [
        "offer_hero",
        "announcement_hero_layout"
      ],
      "visualPriority": "high",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "offer_badge"
      ],
      "score": {
        "promotion": 0.88,
        "announcement": 0.9,
        "product_launch": 0.92,
        "advertisement": 0.72,
        "thought_leadership": 0.45,
        "event": 0.5,
        "case_study": 0.55,
        "feature_release": 0.85,
        "webinar": 0.48,
        "hiring": 0.52
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "hiring_post",
        "quote_card",
        "birthday_invite"
      ]
    },
    {
      "id": "comparison-columns",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "promotion",
        "product_launch"
      ],
      "visualPriority": "high",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "metric"
      ],
      "score": {
        "promotion": 0.88,
        "product_launch": 0.85
      },
      "artifactSupports": [
        "comparison_chart"
      ]
    },
    {
      "id": "contact-footer",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event",
        "announcement"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "center",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "contact"
      ],
      "score": {
        "event": 0.92,
        "announcement": 0.75,
        "thought_leadership": 0.6
      },
      "artifactSupports": [
        "wedding_invite",
        "birthday_invite",
        "rsvp_card",
        "business_card",
        "meetup_poster"
      ]
    },
    {
      "id": "copy-only",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "thought_leadership"
      ],
      "visualPriority": "low",
      "contentDensity": "high",
      "readingPattern": "center",
      "visualWeight": "light",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "quote"
      ],
      "score": {
        "announcement": 0.85,
        "thought_leadership": 0.9
      },
      "artifactSupports": [
        "certificate",
        "quote_card"
      ]
    },
    {
      "id": "copy-statement",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "thought_leadership"
      ],
      "recipes": [
        "narrative_statement",
        "statistic_hero"
      ],
      "visualPriority": "low",
      "contentDensity": "high",
      "readingPattern": "center",
      "visualWeight": "light",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "quote",
        "metric"
      ],
      "score": {
        "promotion": 0.42,
        "announcement": 0.58,
        "product_launch": 0.45,
        "advertisement": 0.48,
        "thought_leadership": 0.95,
        "event": 0.5,
        "case_study": 0.72,
        "feature_release": 0.5,
        "webinar": 0.55,
        "hiring": 0.62
      },
      "artifactSupports": [
        "infographic",
        "timeline",
        "checklist",
        "quote_card",
        "certificate"
      ]
    },
    {
      "id": "deck-sidebar",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "thought_leadership",
        "case_study",
        "webinar",
        "event"
      ],
      "recipes": [
        "narrative_statement",
        "social_proof_strip"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "metric",
        "quote",
        "customer_logo"
      ],
      "score": {
        "promotion": 0.45,
        "announcement": 0.58,
        "product_launch": 0.55,
        "advertisement": 0.52,
        "thought_leadership": 0.9,
        "event": 0.82,
        "case_study": 0.88,
        "feature_release": 0.6,
        "webinar": 0.85,
        "hiring": 0.5
      },
      "artifactSupports": [
        "pitch_deck",
        "webinar_slides",
        "roadmap"
      ]
    },
    {
      "id": "diagram-primary",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "documentation"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "F",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "diagram",
        "product_image"
      ],
      "score": {
        "documentation": 0.95
      },
      "artifactSupports": [
        "flowchart",
        "org_chart",
        "process_flow"
      ]
    },
    {
      "id": "event-footer",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event",
        "webinar"
      ],
      "recipes": [
        "event_footer_recipe"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "cta",
        "product_image",
        "badge"
      ],
      "score": {
        "promotion": 0.45,
        "announcement": 0.58,
        "product_launch": 0.5,
        "advertisement": 0.48,
        "thought_leadership": 0.5,
        "event": 0.95,
        "case_study": 0.48,
        "feature_release": 0.45,
        "webinar": 0.93,
        "hiring": 0.45
      },
      "artifactSupports": [
        "birthday_invite",
        "wedding_invite",
        "meetup_poster",
        "rsvp_card"
      ]
    },
    {
      "id": "event-poster",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event",
        "webinar"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "contact",
        "product_image"
      ],
      "score": {
        "event": 0.98,
        "webinar": 0.9,
        "announcement": 0.72
      },
      "artifactSupports": [
        "meetup_poster",
        "birthday_invite",
        "wedding_invite",
        "rsvp_card"
      ]
    },
    {
      "id": "footer-mark",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event",
        "webinar"
      ],
      "recipes": [
        "event_footer_recipe"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "center",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "product_image",
        "cta",
        "badge"
      ],
      "score": {
        "promotion": 0.45,
        "announcement": 0.6,
        "product_launch": 0.48,
        "advertisement": 0.5,
        "thought_leadership": 0.52,
        "event": 0.95,
        "case_study": 0.5,
        "feature_release": 0.45,
        "webinar": 0.9,
        "hiring": 0.48
      },
      "artifactSupports": [
        "birthday_invite",
        "wedding_invite",
        "rsvp_card"
      ]
    },
    {
      "id": "hiring-post",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "hiring",
        "announcement"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta"
      ],
      "score": {
        "hiring": 0.98,
        "announcement": 0.7
      },
      "artifactSupports": [
        "hiring_post"
      ]
    },
    {
      "id": "invite-card",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "center",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "contact",
        "product_image"
      ],
      "score": {
        "event": 0.96
      },
      "artifactSupports": [
        "birthday_invite",
        "wedding_invite",
        "rsvp_card"
      ]
    },
    {
      "id": "logo-footer-bar",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "case_study",
        "thought_leadership"
      ],
      "recipes": [
        "social_proof_strip",
        "event_footer_recipe"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "product_image",
        "customer_logo",
        "quote",
        "metric"
      ],
      "score": {
        "promotion": 0.48,
        "announcement": 0.65,
        "product_launch": 0.5,
        "advertisement": 0.52,
        "thought_leadership": 0.78,
        "event": 0.72,
        "case_study": 0.9,
        "feature_release": 0.55,
        "webinar": 0.68,
        "hiring": 0.58
      },
      "artifactSupports": [
        "business_card",
        "certificate",
        "linkedin_ad",
        "hiring_post"
      ]
    },
    {
      "id": "product-focus",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "feature_release"
      ],
      "recipes": [
        "offer_hero",
        "comparison_switch",
        "problem_solution_flow"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "F",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "badge",
        "offer_badge"
      ],
      "score": {
        "promotion": 0.78,
        "announcement": 0.6,
        "product_launch": 0.95,
        "advertisement": 0.9,
        "thought_leadership": 0.4,
        "event": 0.45,
        "case_study": 0.55,
        "feature_release": 0.92,
        "webinar": 0.42,
        "hiring": 0.4
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "product_launch",
        "birthday_invite"
      ]
    },
    {
      "id": "professional-left",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "case_study",
        "thought_leadership",
        "feature_release"
      ],
      "recipes": [
        "social_proof_strip",
        "statistic_hero",
        "comparison_switch",
        "narrative_statement"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "product_image",
        "metric",
        "customer_logo",
        "quote"
      ],
      "score": {
        "promotion": 0.5,
        "announcement": 0.7,
        "product_launch": 0.65,
        "advertisement": 0.58,
        "thought_leadership": 0.88,
        "event": 0.52,
        "case_study": 0.9,
        "feature_release": 0.78,
        "webinar": 0.55,
        "hiring": 0.68
      },
      "artifactSupports": [
        "linkedin_ad",
        "hiring_post",
        "business_card",
        "proposal_cover"
      ]
    },
    {
      "id": "proposal-cover",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "thought_leadership"
      ],
      "visualPriority": "low",
      "contentDensity": "low",
      "readingPattern": "center",
      "visualWeight": "light",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body"
      ],
      "score": {
        "announcement": 0.85,
        "thought_leadership": 0.8
      },
      "artifactSupports": [
        "proposal_cover"
      ]
    },
    {
      "id": "section-stack",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "documentation",
        "thought_leadership"
      ],
      "visualPriority": "low",
      "contentDensity": "high",
      "readingPattern": "F",
      "visualWeight": "light",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "metric"
      ],
      "score": {
        "documentation": 0.9,
        "thought_leadership": 0.85
      },
      "artifactSupports": [
        "checklist",
        "timeline",
        "framework",
        "infographic"
      ]
    },
    {
      "id": "social-ad",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "advertisement",
        "promotion",
        "product_launch"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge"
      ],
      "score": {
        "advertisement": 0.95,
        "promotion": 0.92,
        "product_launch": 0.88
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post"
      ]
    },
    {
      "id": "split-feature-left",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "feature_release"
      ],
      "recipes": [
        "problem_solution_flow",
        "comparison_switch"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "Z",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "badge"
      ],
      "score": {
        "promotion": 0.7,
        "announcement": 0.55,
        "product_launch": 0.9,
        "advertisement": 0.88,
        "thought_leadership": 0.45,
        "event": 0.48,
        "case_study": 0.62,
        "feature_release": 0.85,
        "webinar": 0.5,
        "hiring": 0.42
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "birthday_invite",
        "meetup_poster"
      ]
    },
    {
      "id": "split-feature-right",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "feature_release"
      ],
      "recipes": [
        "comparison_switch",
        "problem_solution_flow"
      ],
      "visualPriority": "high",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "metric"
      ],
      "score": {
        "promotion": 0.72,
        "announcement": 0.6,
        "product_launch": 0.88,
        "advertisement": 0.9,
        "thought_leadership": 0.55,
        "event": 0.52,
        "case_study": 0.7,
        "feature_release": 0.85,
        "webinar": 0.55,
        "hiring": 0.45
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "birthday_invite",
        "meetup_poster"
      ]
    },
    {
      "id": "visual-first",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "promotion"
      ],
      "recipes": [
        "offer_hero",
        "announcement_hero_layout"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "center",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "product_image",
        "badge",
        "offer_badge"
      ],
      "score": {
        "promotion": 0.85,
        "announcement": 0.62,
        "product_launch": 0.92,
        "advertisement": 0.93,
        "thought_leadership": 0.4,
        "event": 0.55,
        "case_study": 0.48,
        "feature_release": 0.8,
        "webinar": 0.45,
        "hiring": 0.42
      },
      "artifactSupports": [
        "linkedin_ad",
        "instagram_post",
        "birthday_invite",
        "wedding_invite",
        "meetup_poster"
      ]
    }
  ],
  "systems": [
    {
      "id": "default",
      "label": "Default Design System",
      "campaigns": [
        "announcement",
        "thought_leadership",
        "event",
        "webinar",
        "hiring"
      ],
      "layouts": [
        "classic-hero",
        "centered-announcement",
        "logo-footer-bar",
        "product-focus",
        "copy-statement",
        "balanced-split",
        "visual-first",
        "professional-left",
        "footer-mark",
        "brand-stack",
        "event-footer",
        "split-feature-right",
        "split-feature-left",
        "deck-sidebar"
      ],
      "spacingPreset": "default",
      "typographyPreset": "default",
      "badgeStyles": [
        "default"
      ],
      "ctaStyles": [
        "default"
      ],
      "patterns": [
        "grid",
        "dots",
        "topography",
        "monogram-soft"
      ],
      "illustrationStyles": [
        "default"
      ],
      "decorationLevels": [
        "minimal",
        "brand"
      ],
      "colorMoods": [
        "neutral",
        "enterprise",
        "cool"
      ]
    },
    {
      "id": "enterprise_saas",
      "label": "Enterprise SaaS Design System",
      "campaigns": [
        "product_launch",
        "feature_release",
        "case_study"
      ],
      "layouts": [
        "classic-hero",
        "product-focus",
        "balanced-split",
        "visual-first",
        "professional-left",
        "split-feature-right",
        "split-feature-left",
        "deck-sidebar",
        "logo-footer-bar"
      ],
      "spacingPreset": "default",
      "typographyPreset": "enterprise",
      "badgeStyles": [
        "default"
      ],
      "ctaStyles": [
        "primary",
        "default"
      ],
      "patterns": [
        "grid",
        "topography"
      ],
      "illustrationStyles": [
        "ui",
        "default"
      ],
      "decorationLevels": [
        "minimal"
      ],
      "colorMoods": [
        "enterprise",
        "cool",
        "neutral"
      ]
    },
    {
      "id": "offer",
      "label": "Offer Design System",
      "campaigns": [
        "promotion",
        "advertisement"
      ],
      "layouts": [
        "classic-hero",
        "centered-announcement",
        "product-focus",
        "balanced-split",
        "visual-first",
        "brand-stack",
        "professional-left",
        "split-feature-right",
        "split-feature-left"
      ],
      "spacingPreset": "compact",
      "typographyPreset": "bold",
      "badgeStyles": [
        "offer",
        "default"
      ],
      "ctaStyles": [
        "primary",
        "default"
      ],
      "patterns": [
        "grid",
        "dots",
        "topography"
      ],
      "illustrationStyles": [
        "default"
      ],
      "decorationLevels": [
        "offer",
        "mesh",
        "minimal"
      ],
      "colorMoods": [
        "warm",
        "bold",
        "neutral"
      ]
    }
  ],
  "overlays": [
    {
      "id": "advertisement",
      "label": "Advertisement",
      "platforms": [],
      "formats": [
        "ad"
      ],
      "copyBudget": {
        "headlineWords": 8,
        "subheadingWords": 15,
        "ctaWords": 6,
        "maxTotalWords": 35
      },
      "slotLimits": {
        "headline": 42,
        "subheading": 90,
        "caption": 40,
        "body": 0
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.4,
        "maxCopyWordShare": 0.35,
        "passThreshold": 85
      },
      "requiredSlots": [
        "headline",
        "subheading"
      ],
      "bannedSlots": [
        "body"
      ],
      "maxCopyRetries": 2
    },
    {
      "id": "default",
      "label": "Default",
      "platforms": [],
      "formats": [],
      "copyBudget": {
        "headlineWords": 12,
        "subheadingWords": 24,
        "ctaWords": 8,
        "maxTotalWords": 60
      },
      "slotLimits": {
        "headline": 72,
        "subheading": 140,
        "body": 220,
        "caption": 48
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.3,
        "maxCopyWordShare": 0.45,
        "passThreshold": 80
      },
      "requiredSlots": [
        "headline"
      ],
      "bannedSlots": [],
      "maxCopyRetries": 1
    },
    {
      "id": "linkedin-ad",
      "label": "LinkedIn Ad",
      "platforms": [
        "linkedin"
      ],
      "formats": [
        "ad"
      ],
      "copyBudget": {
        "headlineWords": 8,
        "subheadingWords": 15,
        "ctaWords": 6,
        "maxTotalWords": 35
      },
      "slotLimits": {
        "headline": 42,
        "subheading": 90,
        "caption": 40,
        "body": 0
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.4,
        "maxCopyWordShare": 0.35,
        "passThreshold": 85
      },
      "requiredSlots": [
        "headline",
        "subheading"
      ],
      "bannedSlots": [
        "body"
      ],
      "maxCopyRetries": 2
    },
    {
      "id": "linkedin-post",
      "label": "LinkedIn Post",
      "platforms": [
        "linkedin"
      ],
      "formats": [
        "post"
      ],
      "copyBudget": {
        "headlineWords": 10,
        "subheadingWords": 20,
        "ctaWords": 8,
        "maxTotalWords": 50
      },
      "slotLimits": {
        "headline": 56,
        "subheading": 120,
        "body": 180,
        "caption": 48
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.35,
        "maxCopyWordShare": 0.4,
        "passThreshold": 80
      },
      "requiredSlots": [
        "headline"
      ],
      "bannedSlots": [],
      "maxCopyRetries": 1
    }
  ],
  "visuals": {
    "featured": {
      "promotion": "product_photo",
      "advertisement": "product_ui",
      "product_launch": "product_ui",
      "feature_release": "product_ui",
      "case_study": "metric",
      "announcement": "illustration",
      "thought_leadership": "illustration",
      "event": "people",
      "webinar": "product_ui",
      "hiring": "people",
      "enterprise": "product_ui"
    },
    "pattern": {
      "promotion": "blob",
      "advertisement": "grid",
      "product_launch": "grid",
      "feature_release": "topography",
      "case_study": "grid",
      "announcement": "monogram",
      "thought_leadership": "monogram",
      "event": "grid",
      "webinar": "grid",
      "hiring": "dots",
      "enterprise_saas": "grid"
    },
    "decoration": {
      "promotion": "offer",
      "advertisement": "offer",
      "product_launch": "minimal",
      "feature_release": "minimal",
      "case_study": "minimal",
      "announcement": "brand",
      "thought_leadership": "minimal",
      "event": "minimal",
      "webinar": "minimal",
      "hiring": "minimal"
    },
    "color": {
      "promotion": "warm",
      "advertisement": "bold",
      "product_launch": "enterprise",
      "feature_release": "cool",
      "case_study": "enterprise",
      "announcement": "neutral",
      "thought_leadership": "neutral",
      "event": "cool",
      "webinar": "cool",
      "hiring": "warm",
      "enterprise_saas": "enterprise"
    }
  },
  "blockFamilies": [
    {
      "id": "actions",
      "label": "Actions & CTAs",
      "purpose": [
        "drive_action",
        "contact"
      ],
      "supports": [
        "marketing",
        "events",
        "social",
        "commerce"
      ],
      "hierarchy": "supporting",
      "density": [
        "compact",
        "medium"
      ],
      "compositions": [
        "centered",
        "inline"
      ],
      "stylePacks": [
        "minimal",
        "bold",
        "enterprise"
      ],
      "compatibleRecipes": [
        "invitation_hero",
        "invitation_rsvp",
        "offer_hero",
        "presentation_closing"
      ],
      "assets": [
        {
          "id": "cta-button-primary",
          "kind": "ui",
          "role": "cta"
        },
        {
          "id": "cta-button-outline",
          "kind": "ui",
          "role": "cta"
        },
        {
          "id": "cta-pill-pair",
          "kind": "ui",
          "role": "cta"
        },
        {
          "id": "badge-pill",
          "kind": "ui",
          "role": "badge"
        },
        {
          "id": "contact-row",
          "kind": "ui",
          "role": "contact"
        }
      ]
    },
    {
      "id": "benefits",
      "label": "Benefits",
      "purpose": [
        "explain",
        "list",
        "persuade"
      ],
      "supports": [
        "features",
        "benefits",
        "checklist"
      ],
      "hierarchy": "supporting",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "vertical",
        "centered",
        "editorial"
      ],
      "stylePacks": [
        "enterprise",
        "startup",
        "minimal",
        "editorial",
        "glass"
      ],
      "compatibleRecipes": [
        "offer_hero",
        "problem_solution_flow",
        "feature_launch",
        "announcement_hero_layout"
      ],
      "assets": [
        {
          "id": "feature-list",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "checklist-benefits",
          "kind": "ui",
          "role": "checklist"
        },
        {
          "id": "icon-benefit-row",
          "kind": "ui",
          "role": "icons"
        },
        {
          "id": "benefit-pills",
          "kind": "ui",
          "role": "pills"
        }
      ],
      "illustrationTags": [
        "features",
        "checklist",
        "benefits",
        "list",
        "teamwork"
      ],
      "slots": {
        "title": {
          "optional": true
        },
        "item1": {
          "optional": true
        },
        "item2": {
          "optional": true
        },
        "item3": {
          "optional": true
        }
      }
    },
    {
      "id": "comparison",
      "label": "Comparison",
      "purpose": [
        "compare",
        "contrast",
        "switch"
      ],
      "supports": [
        "before_after",
        "vs",
        "competitive"
      ],
      "hierarchy": "hero",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "split",
        "side-by-side",
        "centered"
      ],
      "stylePacks": [
        "enterprise",
        "startup",
        "bold",
        "minimal",
        "editorial"
      ],
      "compatibleRecipes": [
        "comparison_switch",
        "problem_solution_flow",
        "offer_hero"
      ],
      "assets": [
        {
          "id": "vs-split-card",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "competitor-row",
          "kind": "ui",
          "role": "table"
        },
        {
          "id": "switch-reason",
          "kind": "ui",
          "role": "reasons"
        },
        {
          "id": "comparison-cards",
          "kind": "diagram",
          "role": "cards"
        },
        {
          "id": "before-after",
          "kind": "diagram",
          "role": "variant"
        }
      ],
      "illustrationTags": [
        "comparison",
        "versus",
        "choice",
        "decision",
        "contrast"
      ],
      "slots": {
        "left": {
          "optional": true
        },
        "right": {
          "optional": true
        },
        "title": {
          "optional": true
        }
      }
    },
    {
      "id": "diagram",
      "label": "Diagram",
      "purpose": [
        "structure",
        "connect",
        "integrate"
      ],
      "supports": [
        "hub",
        "network",
        "trend"
      ],
      "hierarchy": "supporting",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "centered",
        "floating"
      ],
      "stylePacks": [
        "enterprise",
        "minimal",
        "editorial",
        "startup"
      ],
      "compatibleRecipes": [
        "problem_solution_flow",
        "process-explain",
        "feature-launch"
      ],
      "assets": [
        {
          "id": "integration-hub",
          "kind": "diagram",
          "role": "primary"
        },
        {
          "id": "line-chart",
          "kind": "diagram",
          "role": "trend"
        }
      ],
      "illustrationTags": [
        "network",
        "connect",
        "integration",
        "system",
        "architecture"
      ],
      "slots": {
        "title": {
          "optional": true
        }
      }
    },
    {
      "id": "metric",
      "label": "Metric",
      "purpose": [
        "prove",
        "quantify"
      ],
      "supports": [
        "roi",
        "percentage",
        "growth",
        "revenue",
        "kpi"
      ],
      "hierarchy": "hero",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "centered",
        "split",
        "editorial",
        "floating"
      ],
      "stylePacks": [
        "enterprise",
        "startup",
        "editorial",
        "glass",
        "bold",
        "minimal",
        "gradient"
      ],
      "compatibleRecipes": [
        "offer_hero",
        "comparison_switch",
        "statistic_hero",
        "social_proof_strip",
        "problem_solution_flow"
      ],
      "assets": [
        {
          "id": "stat-highlight",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "kpi-hero",
          "kind": "ui",
          "role": "hero"
        },
        {
          "id": "growth-badge",
          "kind": "ui",
          "role": "badge"
        },
        {
          "id": "revenue-stat",
          "kind": "ui",
          "role": "revenue"
        },
        {
          "id": "roi-callout",
          "kind": "ui",
          "role": "callout"
        },
        {
          "id": "percent-split",
          "kind": "ui",
          "role": "split"
        },
        {
          "id": "progress-ring",
          "kind": "ui",
          "role": "variant"
        },
        {
          "id": "metric-cards-row",
          "kind": "ui",
          "role": "row"
        },
        {
          "id": "dashboard-metrics",
          "kind": "ui",
          "role": "dashboard"
        },
        {
          "id": "donut-chart",
          "kind": "diagram",
          "role": "chart"
        },
        {
          "id": "bar-chart",
          "kind": "diagram",
          "role": "chart"
        }
      ],
      "illustrationTags": [
        "metric",
        "chart",
        "growth",
        "analytics",
        "success",
        "data",
        "statistics"
      ],
      "slots": {
        "metric": {
          "required": true
        },
        "description": {
          "optional": true
        },
        "cta": {
          "optional": true
        }
      }
    },
    {
      "id": "pricing",
      "label": "Pricing",
      "purpose": [
        "offer",
        "convert",
        "price"
      ],
      "supports": [
        "pricing",
        "plan",
        "tier"
      ],
      "hierarchy": "hero",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "centered",
        "card",
        "floating"
      ],
      "stylePacks": [
        "enterprise",
        "startup",
        "bold",
        "glass",
        "gradient"
      ],
      "compatibleRecipes": [
        "offer_hero",
        "discount_focus",
        "pricing-offer"
      ],
      "assets": [
        {
          "id": "pricing-card",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "dual-pricing",
          "kind": "ui",
          "role": "compare"
        },
        {
          "id": "offer-badge-card",
          "kind": "ui",
          "role": "offer"
        },
        {
          "id": "discount-strip",
          "kind": "ui",
          "role": "discount"
        }
      ],
      "illustrationTags": [
        "pricing",
        "payment",
        "shopping",
        "commerce",
        "money"
      ],
      "slots": {
        "tier": {
          "optional": true
        },
        "price": {
          "required": true
        },
        "cta": {
          "optional": true
        }
      }
    },
    {
      "id": "process",
      "label": "Process",
      "purpose": [
        "explain",
        "sequence",
        "guide"
      ],
      "supports": [
        "steps",
        "timeline",
        "funnel",
        "pipeline"
      ],
      "hierarchy": "supporting",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "horizontal",
        "vertical",
        "centered"
      ],
      "stylePacks": [
        "enterprise",
        "startup",
        "minimal",
        "editorial"
      ],
      "compatibleRecipes": [
        "problem_solution_flow",
        "process-explain",
        "announcement_hero_layout"
      ],
      "assets": [
        {
          "id": "numbered-steps",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "process-cards",
          "kind": "ui",
          "role": "cards"
        },
        {
          "id": "roadmap-strip",
          "kind": "ui",
          "role": "roadmap"
        },
        {
          "id": "timeline",
          "kind": "diagram",
          "role": "timeline"
        },
        {
          "id": "workflow-steps",
          "kind": "diagram",
          "role": "steps"
        },
        {
          "id": "pipeline-flow",
          "kind": "diagram",
          "role": "pipeline"
        },
        {
          "id": "funnel",
          "kind": "diagram",
          "role": "funnel"
        }
      ],
      "illustrationTags": [
        "process",
        "steps",
        "workflow",
        "timeline",
        "journey",
        "path"
      ],
      "slots": {
        "title": {
          "optional": true
        },
        "step1": {
          "optional": true
        },
        "step2": {
          "optional": true
        },
        "step3": {
          "optional": true
        }
      }
    },
    {
      "id": "product",
      "label": "Product",
      "purpose": [
        "show",
        "demonstrate",
        "product_ui"
      ],
      "supports": [
        "ui",
        "dashboard",
        "kanban",
        "table"
      ],
      "hierarchy": "hero",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "centered",
        "frame",
        "split"
      ],
      "stylePacks": [
        "enterprise",
        "startup",
        "glass",
        "minimal",
        "bold"
      ],
      "compatibleRecipes": [
        "problem_solution_flow",
        "offer_hero",
        "announcement_hero_layout",
        "comparison_switch"
      ],
      "assets": [
        {
          "id": "product-frame",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "kanban-board",
          "kind": "ui",
          "role": "board"
        },
        {
          "id": "table-preview",
          "kind": "ui",
          "role": "table"
        },
        {
          "id": "notification-stack",
          "kind": "ui",
          "role": "notifications"
        },
        {
          "id": "calendar-preview",
          "kind": "ui",
          "role": "calendar"
        },
        {
          "id": "chat-thread",
          "kind": "ui",
          "role": "chat"
        },
        {
          "id": "form-card",
          "kind": "ui",
          "role": "form"
        },
        {
          "id": "crm-list",
          "kind": "ui",
          "role": "crm"
        },
        {
          "id": "inbox-preview",
          "kind": "ui",
          "role": "inbox"
        },
        {
          "id": "cta-banner",
          "kind": "ui",
          "role": "cta"
        },
        {
          "id": "value-prop-card",
          "kind": "ui",
          "role": "value"
        }
      ],
      "illustrationTags": [
        "app",
        "interface",
        "dashboard",
        "software",
        "device",
        "screen"
      ],
      "slots": {
        "title": {
          "optional": true
        }
      }
    },
    {
      "id": "proof",
      "label": "Proof",
      "purpose": [
        "trust",
        "social_proof",
        "testify"
      ],
      "supports": [
        "quote",
        "testimonial",
        "review"
      ],
      "hierarchy": "supporting",
      "density": [
        "compact",
        "medium",
        "hero"
      ],
      "compositions": [
        "centered",
        "editorial",
        "floating"
      ],
      "stylePacks": [
        "enterprise",
        "editorial",
        "glass",
        "minimal",
        "startup"
      ],
      "compatibleRecipes": [
        "social_proof_strip",
        "statistic_hero",
        "offer_hero",
        "case_study"
      ],
      "assets": [
        {
          "id": "testimonial-card",
          "kind": "ui",
          "role": "primary"
        },
        {
          "id": "quote-highlight",
          "kind": "ui",
          "role": "variant"
        },
        {
          "id": "logo-wall",
          "kind": "ui",
          "role": "logos"
        },
        {
          "id": "star-review",
          "kind": "ui",
          "role": "rating"
        },
        {
          "id": "case-study-card",
          "kind": "ui",
          "role": "case"
        },
        {
          "id": "trust-badges",
          "kind": "ui",
          "role": "badges"
        },
        {
          "id": "avatar-stack",
          "kind": "ui",
          "role": "social"
        }
      ],
      "illustrationTags": [
        "testimonial",
        "review",
        "customer",
        "trust",
        "feedback",
        "people"
      ],
      "slots": {
        "quote": {
          "required": true
        },
        "name": {
          "optional": true
        },
        "role": {
          "optional": true
        }
      }
    }
  ],
  "blockBundles": [
    {
      "id": "feature-launch",
      "purpose": "Explain a new capability with product proof",
      "contains": [
        {
          "family": "product",
          "hierarchy": "hero",
          "density": "medium"
        },
        {
          "family": "benefits",
          "hierarchy": "supporting",
          "density": "compact"
        }
      ],
      "worksFor": [
        "linkedin-square",
        "linkedin-landscape",
        "instagram-square"
      ],
      "campaigns": [
        "feature_release",
        "product_launch",
        "announcement"
      ],
      "compatibleRecipes": [
        "problem_solution_flow",
        "announcement_hero_layout",
        "offer_hero"
      ]
    },
    {
      "id": "growth-proof",
      "purpose": "Build trust with a quantified outcome",
      "contains": [
        {
          "family": "metric",
          "hierarchy": "hero",
          "density": "medium"
        },
        {
          "family": "proof",
          "hierarchy": "supporting",
          "density": "compact"
        }
      ],
      "worksFor": [
        "linkedin-square",
        "linkedin-landscape",
        "instagram-square"
      ],
      "campaigns": [
        "promotion",
        "product_launch",
        "advertisement",
        "case_study",
        "feature_release"
      ],
      "compatibleRecipes": [
        "offer_hero",
        "comparison_switch",
        "statistic_hero",
        "social_proof_strip"
      ]
    },
    {
      "id": "pricing-offer",
      "purpose": "Present an offer with clear pricing and CTA",
      "contains": [
        {
          "family": "pricing",
          "hierarchy": "hero",
          "density": "medium"
        },
        {
          "family": "benefits",
          "hierarchy": "supporting",
          "density": "compact"
        }
      ],
      "worksFor": [
        "linkedin-square",
        "linkedin-landscape",
        "instagram-square"
      ],
      "campaigns": [
        "promotion",
        "advertisement"
      ],
      "compatibleRecipes": [
        "offer_hero",
        "discount_focus"
      ]
    },
    {
      "id": "process-explain",
      "purpose": "Walk through a process or workflow",
      "contains": [
        {
          "family": "process",
          "hierarchy": "hero",
          "density": "medium"
        },
        {
          "family": "diagram",
          "hierarchy": "supporting",
          "density": "compact"
        }
      ],
      "worksFor": [
        "linkedin-square",
        "linkedin-landscape"
      ],
      "campaigns": [
        "product_launch",
        "feature_release",
        "thought_leadership",
        "webinar"
      ],
      "compatibleRecipes": [
        "problem_solution_flow",
        "announcement_hero_layout"
      ]
    },
    {
      "id": "social-proof",
      "purpose": "Establish trust via quotes and social signals",
      "contains": [
        {
          "family": "proof",
          "hierarchy": "hero",
          "density": "medium"
        },
        {
          "family": "metric",
          "hierarchy": "supporting",
          "density": "compact"
        }
      ],
      "worksFor": [
        "linkedin-square",
        "linkedin-landscape"
      ],
      "campaigns": [
        "case_study",
        "product_launch",
        "advertisement",
        "thought_leadership"
      ],
      "compatibleRecipes": [
        "social_proof_strip",
        "statistic_hero"
      ]
    }
  ],
  "stylePacks": [
    {
      "id": "bold",
      "label": "Bold",
      "radius": "md",
      "shadow": "bold",
      "border": "strong",
      "spacing": "comfortable",
      "typography": "display",
      "elevation": "high",
      "surface": "solid"
    },
    {
      "id": "editorial",
      "label": "Editorial",
      "radius": "sm",
      "shadow": "none",
      "border": "hairline",
      "spacing": "airy",
      "typography": "editorial",
      "elevation": "flat",
      "surface": "minimal"
    },
    {
      "id": "enterprise",
      "label": "Enterprise",
      "radius": "md",
      "shadow": "soft",
      "border": "hairline",
      "spacing": "comfortable",
      "typography": "sans-tight",
      "elevation": "low",
      "surface": "solid"
    },
    {
      "id": "glass",
      "label": "Glass",
      "radius": "lg",
      "shadow": "soft",
      "border": "hairline",
      "spacing": "comfortable",
      "typography": "sans-tight",
      "elevation": "low",
      "surface": "glass"
    },
    {
      "id": "gradient",
      "label": "Gradient",
      "radius": "lg",
      "shadow": "medium",
      "border": "none",
      "spacing": "comfortable",
      "typography": "display",
      "elevation": "medium",
      "surface": "gradient"
    },
    {
      "id": "minimal",
      "label": "Minimal",
      "radius": "sm",
      "shadow": "none",
      "border": "none",
      "spacing": "tight",
      "typography": "sans-tight",
      "elevation": "flat",
      "surface": "minimal"
    },
    {
      "id": "startup",
      "label": "Startup",
      "radius": "lg",
      "shadow": "medium",
      "border": "none",
      "spacing": "comfortable",
      "typography": "sans-roomy",
      "elevation": "medium",
      "surface": "solid"
    }
  ],
  "illustrationMap": {
    "families": {
      "metric": [
        "metric",
        "chart",
        "growth",
        "analytics",
        "success",
        "data",
        "statistics",
        "roi"
      ],
      "comparison": [
        "comparison",
        "versus",
        "choice",
        "decision",
        "contrast"
      ],
      "benefits": [
        "features",
        "checklist",
        "benefits",
        "list",
        "teamwork"
      ],
      "proof": [
        "testimonial",
        "review",
        "customer",
        "trust",
        "feedback",
        "people",
        "quote"
      ],
      "pricing": [
        "pricing",
        "payment",
        "shopping",
        "commerce",
        "money"
      ],
      "process": [
        "process",
        "steps",
        "workflow",
        "timeline",
        "journey",
        "path"
      ],
      "product": [
        "app",
        "interface",
        "dashboard",
        "software",
        "device",
        "screen"
      ],
      "diagram": [
        "network",
        "connect",
        "integration",
        "system",
        "architecture"
      ]
    }
  }
} as const;
