/* AUTO-GENERATED by scripts/compile-design-config.mjs — do not edit by hand */
/* eslint-disable */
export const designConfigData = {
  "campaigns": [
    {
      "campaign": "advertisement",
      "label": "Advertisement",
      "designSystem": "offer",
      "headline": {
        "maxWords": 8,
        "emphasis": "offer"
      },
      "subheading": {
        "optional": false,
        "maxWords": 15
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 35
      },
      "spacing": "compact",
      "patterns": [
        "grid",
        "dots"
      ],
      "requiredSlots": [
        "headline",
        "subheading",
        "cta",
        "product_image"
      ],
      "bannedSlots": [
        "body"
      ],
      "defaultPattern": "offer",
      "defaultRecipes": [
        "offer_hero",
        "discount_focus"
      ]
    },
    {
      "campaign": "announcement",
      "label": "Announcement",
      "designSystem": "default",
      "headline": {
        "maxWords": 10,
        "emphasis": "message"
      },
      "subheading": {
        "optional": true,
        "maxWords": 18
      },
      "image": {
        "optional": true
      },
      "cta": {
        "optional": true
      },
      "badge": {
        "optional": true
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 50
      },
      "spacing": "relaxed",
      "patterns": [
        "grid",
        "monogram"
      ],
      "requiredSlots": [
        "headline"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center",
        "announcement_hero_layout"
      ]
    },
    {
      "campaign": "case_study",
      "label": "Case Study",
      "designSystem": "enterprise_saas",
      "headline": {
        "maxWords": 10,
        "emphasis": "outcome"
      },
      "customerLogo": {
        "required": true
      },
      "quote": {
        "required": true
      },
      "metric": {
        "required": true
      },
      "cta": {
        "required": true,
        "type": "learn_more"
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 55
      },
      "spacing": "relaxed",
      "patterns": [
        "grid"
      ],
      "requiredSlots": [
        "headline",
        "quote",
        "metric",
        "customer_logo",
        "cta"
      ],
      "defaultPattern": "social_proof",
      "defaultRecipes": [
        "social_proof_strip",
        "statistic_hero"
      ]
    },
    {
      "campaign": "event",
      "label": "Event",
      "designSystem": "default",
      "headline": {
        "maxWords": 10,
        "emphasis": "event"
      },
      "cta": {
        "required": true,
        "type": "register"
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 45
      },
      "spacing": "default",
      "patterns": [
        "grid"
      ],
      "requiredSlots": [
        "headline",
        "cta"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center",
        "event_footer_recipe"
      ]
    },
    {
      "campaign": "feature_release",
      "label": "Feature Release",
      "designSystem": "enterprise_saas",
      "headline": {
        "maxWords": 8,
        "emphasis": "feature"
      },
      "subheading": {
        "optional": true,
        "maxWords": 16
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 40
      },
      "spacing": "default",
      "patterns": [
        "grid",
        "topography"
      ],
      "requiredSlots": [
        "headline",
        "product_image",
        "cta"
      ],
      "defaultPattern": "problem_solution",
      "defaultRecipes": [
        "problem_solution_flow",
        "offer_hero"
      ]
    },
    {
      "campaign": "hiring",
      "label": "Hiring",
      "designSystem": "default",
      "headline": {
        "maxWords": 8,
        "emphasis": "role"
      },
      "cta": {
        "required": true,
        "type": "apply"
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 45
      },
      "spacing": "default",
      "patterns": [
        "dots"
      ],
      "requiredSlots": [
        "headline",
        "cta"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center"
      ]
    },
    {
      "campaign": "product_launch",
      "label": "Product Launch",
      "designSystem": "enterprise_saas",
      "headline": {
        "maxWords": 8,
        "emphasis": "product"
      },
      "subheading": {
        "optional": true,
        "maxWords": 16
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 40
      },
      "spacing": "default",
      "patterns": [
        "grid",
        "topography"
      ],
      "requiredSlots": [
        "headline",
        "product_image",
        "cta"
      ],
      "defaultPattern": "comparison",
      "defaultRecipes": [
        "comparison_switch",
        "offer_hero",
        "problem_solution_flow"
      ]
    },
    {
      "campaign": "promotion",
      "label": "Promotion",
      "designSystem": "offer",
      "headline": {
        "maxWords": 6,
        "emphasis": "offer"
      },
      "subheading": {
        "optional": true,
        "maxWords": 12
      },
      "offerBadge": {
        "required": true
      },
      "cta": {
        "required": true
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "low",
        "maxTotalWords": 35
      },
      "spacing": "compact",
      "patterns": [
        "gradient_blob",
        "dots",
        "mesh"
      ],
      "requiredSlots": [
        "headline",
        "cta",
        "product_image"
      ],
      "bannedSlots": [
        "body"
      ],
      "defaultPattern": "offer",
      "defaultRecipes": [
        "offer_hero",
        "discount_focus"
      ]
    },
    {
      "campaign": "thought_leadership",
      "label": "Thought Leadership",
      "designSystem": "default",
      "headline": {
        "maxWords": 12,
        "emphasis": "insight"
      },
      "subheading": {
        "optional": true,
        "maxWords": 24
      },
      "cta": {
        "optional": true
      },
      "copy": {
        "density": "high",
        "maxTotalWords": 60
      },
      "spacing": "relaxed",
      "patterns": [
        "monogram"
      ],
      "requiredSlots": [
        "headline"
      ],
      "defaultPattern": "narrative",
      "defaultRecipes": [
        "narrative_statement"
      ]
    },
    {
      "campaign": "webinar",
      "label": "Webinar",
      "designSystem": "default",
      "headline": {
        "maxWords": 10,
        "emphasis": "topic"
      },
      "cta": {
        "required": true,
        "type": "register"
      },
      "featured": {
        "required": true
      },
      "copy": {
        "density": "medium",
        "maxTotalWords": 45
      },
      "spacing": "default",
      "patterns": [
        "grid"
      ],
      "requiredSlots": [
        "headline",
        "cta",
        "product_image"
      ],
      "defaultPattern": "announcement_hero",
      "defaultRecipes": [
        "announcement_center",
        "event_footer_recipe"
      ]
    }
  ],
  "patterns": [
    {
      "id": "announcement_hero",
      "label": "Announcement Hero",
      "description": "Centered message-first announcement.",
      "flow": [
        "Message",
        "Support",
        "Optional CTA"
      ],
      "recipes": [
        "announcement_center",
        "announcement_hero_layout",
        "event_footer_recipe"
      ],
      "campaigns": [
        "announcement",
        "event",
        "webinar",
        "hiring",
        "product_launch"
      ]
    },
    {
      "id": "comparison",
      "label": "Comparison",
      "description": "Old way versus new way, then switch CTA.",
      "flow": [
        "Old Way",
        "New Way",
        "Switch"
      ],
      "recipes": [
        "comparison_switch"
      ],
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement",
        "promotion"
      ]
    },
    {
      "id": "narrative",
      "label": "Narrative",
      "description": "Copy-led storytelling and thought leadership.",
      "flow": [
        "Insight",
        "Context",
        "Soft CTA"
      ],
      "recipes": [
        "narrative_statement"
      ],
      "campaigns": [
        "thought_leadership",
        "announcement"
      ]
    },
    {
      "id": "offer",
      "label": "Offer",
      "description": "Lead with the offer, create urgency, drive CTA.",
      "flow": [
        "Offer",
        "Urgency",
        "CTA"
      ],
      "recipes": [
        "offer_hero",
        "discount_focus"
      ],
      "campaigns": [
        "promotion",
        "advertisement",
        "product_launch"
      ]
    },
    {
      "id": "problem_solution",
      "label": "Problem to Solution",
      "description": "Surface pain, present the solution, drive action.",
      "flow": [
        "Pain",
        "Solution",
        "Action"
      ],
      "recipes": [
        "problem_solution_flow"
      ],
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement"
      ]
    },
    {
      "id": "social_proof",
      "label": "Social Proof",
      "description": "Trust signals via logos, quotes, and outcomes.",
      "flow": [
        "Trusted By",
        "Customer Logos",
        "CTA"
      ],
      "recipes": [
        "social_proof_strip"
      ],
      "campaigns": [
        "case_study",
        "product_launch",
        "advertisement"
      ]
    },
    {
      "id": "statistic",
      "label": "Statistic",
      "description": "Lead with a bold metric, explain, then CTA.",
      "flow": [
        "Metric",
        "Explanation",
        "CTA"
      ],
      "recipes": [
        "statistic_hero"
      ],
      "campaigns": [
        "case_study",
        "thought_leadership",
        "product_launch"
      ]
    }
  ],
  "recipes": [
    {
      "id": "announcement_center",
      "name": "Announcement Center",
      "pattern": "announcement_hero",
      "slots": [
        "logo",
        "badge",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "message",
      "proof": "badge",
      "density": "medium",
      "readingPattern": "center",
      "campaigns": [
        "announcement",
        "hiring",
        "webinar"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "brand-stack",
        "classic-hero"
      ]
    },
    {
      "id": "announcement_hero_layout",
      "name": "Announcement Hero Layout",
      "pattern": "announcement_hero",
      "slots": [
        "logo",
        "headline",
        "product_image",
        "cta"
      ],
      "attention": "message",
      "proof": "screenshot",
      "density": "low",
      "readingPattern": "F",
      "campaigns": [
        "announcement",
        "product_launch"
      ],
      "preferredLayouts": [
        "classic-hero",
        "visual-first",
        "product-focus"
      ]
    },
    {
      "id": "comparison_switch",
      "name": "Comparison Switch",
      "pattern": "comparison",
      "slots": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "cta"
      ],
      "attention": "new_way",
      "proof": "screenshot",
      "density": "low",
      "readingPattern": "Z",
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement",
        "promotion"
      ],
      "preferredLayouts": [
        "balanced-split",
        "split-feature-right",
        "professional-left",
        "product-focus"
      ]
    },
    {
      "id": "discount_focus",
      "name": "Discount Focus",
      "pattern": "offer",
      "slots": [
        "logo",
        "offer_badge",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "offer",
      "proof": "badge",
      "density": "low",
      "readingPattern": "center",
      "campaigns": [
        "promotion",
        "advertisement"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "brand-stack",
        "classic-hero"
      ]
    },
    {
      "id": "event_footer_recipe",
      "name": "Event Footer",
      "pattern": "announcement_hero",
      "slots": [
        "logo",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "event",
      "proof": "none",
      "density": "medium",
      "readingPattern": "F",
      "campaigns": [
        "event",
        "webinar"
      ],
      "preferredLayouts": [
        "event-footer",
        "footer-mark",
        "logo-footer-bar",
        "centered-announcement"
      ]
    },
    {
      "id": "narrative_statement",
      "name": "Narrative Statement",
      "pattern": "narrative",
      "slots": [
        "logo",
        "headline",
        "body",
        "caption"
      ],
      "attention": "insight",
      "proof": "none",
      "density": "high",
      "readingPattern": "F",
      "campaigns": [
        "thought_leadership",
        "announcement"
      ],
      "preferredLayouts": [
        "copy-statement",
        "deck-sidebar",
        "professional-left"
      ]
    },
    {
      "id": "offer_hero",
      "name": "Offer Hero",
      "pattern": "offer",
      "slots": [
        "logo",
        "offer_badge",
        "headline",
        "product_image",
        "cta"
      ],
      "attention": "offer",
      "proof": "badge",
      "density": "low",
      "readingPattern": "F",
      "campaigns": [
        "promotion",
        "advertisement",
        "product_launch"
      ],
      "preferredLayouts": [
        "classic-hero",
        "visual-first",
        "product-focus",
        "balanced-split"
      ]
    },
    {
      "id": "problem_solution_flow",
      "name": "Problem Solution Flow",
      "pattern": "problem_solution",
      "slots": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "cta"
      ],
      "attention": "solution",
      "proof": "screenshot",
      "density": "low",
      "readingPattern": "Z",
      "campaigns": [
        "product_launch",
        "feature_release",
        "advertisement"
      ],
      "preferredLayouts": [
        "balanced-split",
        "split-feature-right",
        "split-feature-left",
        "product-focus"
      ]
    },
    {
      "id": "social_proof_strip",
      "name": "Social Proof Strip",
      "pattern": "social_proof",
      "slots": [
        "logo",
        "headline",
        "customer_logo",
        "quote",
        "cta"
      ],
      "attention": "trust",
      "proof": "logos",
      "density": "medium",
      "readingPattern": "F",
      "campaigns": [
        "case_study",
        "product_launch"
      ],
      "preferredLayouts": [
        "professional-left",
        "logo-footer-bar",
        "brand-stack",
        "deck-sidebar"
      ]
    },
    {
      "id": "statistic_hero",
      "name": "Statistic Hero",
      "pattern": "statistic",
      "slots": [
        "logo",
        "metric",
        "headline",
        "subheading",
        "cta"
      ],
      "attention": "metric",
      "proof": "stat",
      "density": "low",
      "readingPattern": "center",
      "campaigns": [
        "case_study",
        "thought_leadership",
        "product_launch"
      ],
      "preferredLayouts": [
        "centered-announcement",
        "copy-statement",
        "professional-left"
      ]
    }
  ],
  "layouts": [
    {
      "id": "balanced-split",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "advertisement",
        "product_launch",
        "promotion",
        "feature_release",
        "case_study"
      ],
      "recipes": [
        "comparison_switch",
        "problem_solution_flow",
        "offer_hero"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "offer_badge",
        "metric"
      ],
      "score": {
        "promotion": 0.82,
        "announcement": 0.68,
        "product_launch": 0.85,
        "advertisement": 0.88,
        "thought_leadership": 0.55,
        "event": 0.5,
        "case_study": 0.75,
        "feature_release": 0.8,
        "webinar": 0.52,
        "hiring": 0.48
      }
    },
    {
      "id": "brand-stack",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "promotion"
      ],
      "recipes": [
        "discount_focus",
        "announcement_center",
        "social_proof_strip"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "offer_badge",
        "customer_logo"
      ],
      "score": {
        "promotion": 0.88,
        "announcement": 0.9,
        "product_launch": 0.65,
        "advertisement": 0.72,
        "thought_leadership": 0.55,
        "event": 0.5,
        "case_study": 0.58,
        "feature_release": 0.6,
        "webinar": 0.48,
        "hiring": 0.62
      }
    },
    {
      "id": "centered-announcement",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "hiring"
      ],
      "recipes": [
        "announcement_center",
        "discount_focus",
        "statistic_hero"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "center",
      "visualWeight": "medium",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "badge",
        "offer_badge",
        "metric"
      ],
      "score": {
        "promotion": 0.7,
        "announcement": 0.95,
        "product_launch": 0.62,
        "advertisement": 0.58,
        "thought_leadership": 0.55,
        "event": 0.5,
        "case_study": 0.45,
        "feature_release": 0.6,
        "webinar": 0.48,
        "hiring": 0.9
      }
    },
    {
      "id": "classic-hero",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "announcement",
        "product_launch",
        "promotion"
      ],
      "recipes": [
        "offer_hero",
        "announcement_hero_layout"
      ],
      "visualPriority": "high",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "offer_badge"
      ],
      "score": {
        "promotion": 0.88,
        "announcement": 0.9,
        "product_launch": 0.92,
        "advertisement": 0.72,
        "thought_leadership": 0.45,
        "event": 0.5,
        "case_study": 0.55,
        "feature_release": 0.85,
        "webinar": 0.48,
        "hiring": 0.52
      }
    },
    {
      "id": "copy-statement",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "thought_leadership"
      ],
      "recipes": [
        "narrative_statement",
        "statistic_hero"
      ],
      "visualPriority": "low",
      "contentDensity": "high",
      "readingPattern": "center",
      "visualWeight": "light",
      "densityClass": "copyHeavy",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "quote",
        "metric"
      ],
      "score": {
        "promotion": 0.42,
        "announcement": 0.58,
        "product_launch": 0.45,
        "advertisement": 0.48,
        "thought_leadership": 0.95,
        "event": 0.5,
        "case_study": 0.72,
        "feature_release": 0.5,
        "webinar": 0.55,
        "hiring": 0.62
      }
    },
    {
      "id": "deck-sidebar",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "thought_leadership",
        "case_study",
        "webinar",
        "event"
      ],
      "recipes": [
        "narrative_statement",
        "social_proof_strip"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "metric",
        "quote",
        "customer_logo"
      ],
      "score": {
        "promotion": 0.45,
        "announcement": 0.58,
        "product_launch": 0.55,
        "advertisement": 0.52,
        "thought_leadership": 0.9,
        "event": 0.82,
        "case_study": 0.88,
        "feature_release": 0.6,
        "webinar": 0.85,
        "hiring": 0.5
      }
    },
    {
      "id": "event-footer",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event",
        "webinar"
      ],
      "recipes": [
        "event_footer_recipe"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "cta",
        "product_image",
        "badge"
      ],
      "score": {
        "promotion": 0.45,
        "announcement": 0.58,
        "product_launch": 0.5,
        "advertisement": 0.48,
        "thought_leadership": 0.5,
        "event": 0.95,
        "case_study": 0.48,
        "feature_release": 0.45,
        "webinar": 0.93,
        "hiring": 0.45
      }
    },
    {
      "id": "footer-mark",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "event",
        "webinar"
      ],
      "recipes": [
        "event_footer_recipe"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "center",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "product_image",
        "cta",
        "badge"
      ],
      "score": {
        "promotion": 0.45,
        "announcement": 0.6,
        "product_launch": 0.48,
        "advertisement": 0.5,
        "thought_leadership": 0.52,
        "event": 0.95,
        "case_study": 0.5,
        "feature_release": 0.45,
        "webinar": 0.9,
        "hiring": 0.48
      }
    },
    {
      "id": "logo-footer-bar",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "case_study",
        "thought_leadership"
      ],
      "recipes": [
        "social_proof_strip",
        "event_footer_recipe"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "product_image",
        "customer_logo",
        "quote",
        "metric"
      ],
      "score": {
        "promotion": 0.48,
        "announcement": 0.65,
        "product_launch": 0.5,
        "advertisement": 0.52,
        "thought_leadership": 0.78,
        "event": 0.72,
        "case_study": 0.9,
        "feature_release": 0.55,
        "webinar": 0.68,
        "hiring": 0.58
      }
    },
    {
      "id": "product-focus",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "feature_release"
      ],
      "recipes": [
        "offer_hero",
        "comparison_switch",
        "problem_solution_flow"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "F",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "badge",
        "offer_badge"
      ],
      "score": {
        "promotion": 0.78,
        "announcement": 0.6,
        "product_launch": 0.95,
        "advertisement": 0.9,
        "thought_leadership": 0.4,
        "event": 0.45,
        "case_study": 0.55,
        "feature_release": 0.92,
        "webinar": 0.42,
        "hiring": 0.4
      }
    },
    {
      "id": "professional-left",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "case_study",
        "thought_leadership",
        "feature_release"
      ],
      "recipes": [
        "social_proof_strip",
        "statistic_hero",
        "comparison_switch",
        "narrative_statement"
      ],
      "visualPriority": "medium",
      "contentDensity": "medium",
      "readingPattern": "F",
      "visualWeight": "medium",
      "densityClass": "balanced",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "body",
        "cta",
        "product_image",
        "metric",
        "customer_logo",
        "quote"
      ],
      "score": {
        "promotion": 0.5,
        "announcement": 0.7,
        "product_launch": 0.65,
        "advertisement": 0.58,
        "thought_leadership": 0.88,
        "event": 0.52,
        "case_study": 0.9,
        "feature_release": 0.78,
        "webinar": 0.55,
        "hiring": 0.68
      }
    },
    {
      "id": "split-feature-left",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "feature_release"
      ],
      "recipes": [
        "problem_solution_flow",
        "comparison_switch"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "Z",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "product_image",
        "badge"
      ],
      "score": {
        "promotion": 0.7,
        "announcement": 0.55,
        "product_launch": 0.9,
        "advertisement": 0.88,
        "thought_leadership": 0.45,
        "event": 0.48,
        "case_study": 0.62,
        "feature_release": 0.85,
        "webinar": 0.5,
        "hiring": 0.42
      }
    },
    {
      "id": "split-feature-right",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "feature_release"
      ],
      "recipes": [
        "comparison_switch",
        "problem_solution_flow"
      ],
      "visualPriority": "high",
      "contentDensity": "medium",
      "readingPattern": "Z",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "cta",
        "product_image",
        "badge",
        "metric"
      ],
      "score": {
        "promotion": 0.72,
        "announcement": 0.6,
        "product_launch": 0.88,
        "advertisement": 0.9,
        "thought_leadership": 0.55,
        "event": 0.52,
        "case_study": 0.7,
        "feature_release": 0.85,
        "webinar": 0.55,
        "hiring": 0.45
      }
    },
    {
      "id": "visual-first",
      "platforms": [
        "all"
      ],
      "campaigns": [
        "product_launch",
        "advertisement",
        "promotion"
      ],
      "recipes": [
        "offer_hero",
        "announcement_hero_layout"
      ],
      "visualPriority": "high",
      "contentDensity": "low",
      "readingPattern": "center",
      "visualWeight": "heavy",
      "densityClass": "visualFirst",
      "supports": [
        "logo",
        "headline",
        "subheading",
        "caption",
        "product_image",
        "badge",
        "offer_badge"
      ],
      "score": {
        "promotion": 0.85,
        "announcement": 0.62,
        "product_launch": 0.92,
        "advertisement": 0.93,
        "thought_leadership": 0.4,
        "event": 0.55,
        "case_study": 0.48,
        "feature_release": 0.8,
        "webinar": 0.45,
        "hiring": 0.42
      }
    }
  ],
  "systems": [
    {
      "id": "default",
      "label": "Default Design System",
      "campaigns": [
        "announcement",
        "thought_leadership",
        "event",
        "webinar",
        "hiring"
      ],
      "layouts": [
        "classic-hero",
        "centered-announcement",
        "logo-footer-bar",
        "product-focus",
        "copy-statement",
        "balanced-split",
        "visual-first",
        "professional-left",
        "footer-mark",
        "brand-stack",
        "event-footer",
        "split-feature-right",
        "split-feature-left",
        "deck-sidebar"
      ],
      "spacingPreset": "default",
      "typographyPreset": "default",
      "badgeStyles": [
        "default"
      ],
      "ctaStyles": [
        "default"
      ],
      "patterns": [
        "grid",
        "dots",
        "topography",
        "monogram-soft"
      ],
      "illustrationStyles": [
        "default"
      ],
      "decorationLevels": [
        "minimal",
        "brand"
      ],
      "colorMoods": [
        "neutral",
        "enterprise",
        "cool"
      ]
    },
    {
      "id": "enterprise_saas",
      "label": "Enterprise SaaS Design System",
      "campaigns": [
        "product_launch",
        "feature_release",
        "case_study"
      ],
      "layouts": [
        "classic-hero",
        "product-focus",
        "balanced-split",
        "visual-first",
        "professional-left",
        "split-feature-right",
        "split-feature-left",
        "deck-sidebar",
        "logo-footer-bar"
      ],
      "spacingPreset": "default",
      "typographyPreset": "enterprise",
      "badgeStyles": [
        "default"
      ],
      "ctaStyles": [
        "primary",
        "default"
      ],
      "patterns": [
        "grid",
        "topography"
      ],
      "illustrationStyles": [
        "ui",
        "default"
      ],
      "decorationLevels": [
        "minimal"
      ],
      "colorMoods": [
        "enterprise",
        "cool",
        "neutral"
      ]
    },
    {
      "id": "offer",
      "label": "Offer Design System",
      "campaigns": [
        "promotion",
        "advertisement"
      ],
      "layouts": [
        "classic-hero",
        "centered-announcement",
        "product-focus",
        "balanced-split",
        "visual-first",
        "brand-stack",
        "professional-left",
        "split-feature-right",
        "split-feature-left"
      ],
      "spacingPreset": "compact",
      "typographyPreset": "bold",
      "badgeStyles": [
        "offer",
        "default"
      ],
      "ctaStyles": [
        "primary",
        "default"
      ],
      "patterns": [
        "grid",
        "dots",
        "topography"
      ],
      "illustrationStyles": [
        "default"
      ],
      "decorationLevels": [
        "offer",
        "mesh",
        "minimal"
      ],
      "colorMoods": [
        "warm",
        "bold",
        "neutral"
      ]
    }
  ],
  "overlays": [
    {
      "id": "advertisement",
      "label": "Advertisement",
      "platforms": [],
      "formats": [
        "ad"
      ],
      "copyBudget": {
        "headlineWords": 8,
        "subheadingWords": 15,
        "ctaWords": 6,
        "maxTotalWords": 35
      },
      "slotLimits": {
        "headline": 42,
        "subheading": 90,
        "caption": 40,
        "body": 0
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.4,
        "maxCopyWordShare": 0.35,
        "passThreshold": 85
      },
      "requiredSlots": [
        "headline",
        "subheading"
      ],
      "bannedSlots": [
        "body"
      ],
      "maxCopyRetries": 2
    },
    {
      "id": "default",
      "label": "Default",
      "platforms": [],
      "formats": [],
      "copyBudget": {
        "headlineWords": 12,
        "subheadingWords": 24,
        "ctaWords": 8,
        "maxTotalWords": 60
      },
      "slotLimits": {
        "headline": 72,
        "subheading": 140,
        "body": 220,
        "caption": 48
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.3,
        "maxCopyWordShare": 0.45,
        "passThreshold": 80
      },
      "requiredSlots": [
        "headline"
      ],
      "bannedSlots": [],
      "maxCopyRetries": 1
    },
    {
      "id": "linkedin-ad",
      "label": "LinkedIn Ad",
      "platforms": [
        "linkedin"
      ],
      "formats": [
        "ad"
      ],
      "copyBudget": {
        "headlineWords": 8,
        "subheadingWords": 15,
        "ctaWords": 6,
        "maxTotalWords": 35
      },
      "slotLimits": {
        "headline": 42,
        "subheading": 90,
        "caption": 40,
        "body": 0
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.4,
        "maxCopyWordShare": 0.35,
        "passThreshold": 85
      },
      "requiredSlots": [
        "headline",
        "subheading"
      ],
      "bannedSlots": [
        "body"
      ],
      "maxCopyRetries": 2
    },
    {
      "id": "linkedin-post",
      "label": "LinkedIn Post",
      "platforms": [
        "linkedin"
      ],
      "formats": [
        "post"
      ],
      "copyBudget": {
        "headlineWords": 10,
        "subheadingWords": 20,
        "ctaWords": 8,
        "maxTotalWords": 50
      },
      "slotLimits": {
        "headline": 56,
        "subheading": 120,
        "body": 180,
        "caption": 48
      },
      "layoutPolicy": "auto_by_density",
      "featuredPolicy": "library",
      "patternPolicy": "layout_based",
      "backgroundPolicy": "catalog_pick",
      "visualBalance": {
        "minFeaturedShare": 0.35,
        "maxCopyWordShare": 0.4,
        "passThreshold": 80
      },
      "requiredSlots": [
        "headline"
      ],
      "bannedSlots": [],
      "maxCopyRetries": 1
    }
  ],
  "visuals": {
    "featured": {
      "promotion": "product_photo",
      "advertisement": "product_ui",
      "product_launch": "product_ui",
      "feature_release": "product_ui",
      "case_study": "metric",
      "announcement": "illustration",
      "thought_leadership": "illustration",
      "event": "people",
      "webinar": "product_ui",
      "hiring": "people",
      "enterprise": "product_ui"
    },
    "pattern": {
      "promotion": "blob",
      "advertisement": "grid",
      "product_launch": "grid",
      "feature_release": "topography",
      "case_study": "grid",
      "announcement": "monogram",
      "thought_leadership": "monogram",
      "event": "grid",
      "webinar": "grid",
      "hiring": "dots",
      "enterprise_saas": "grid"
    },
    "decoration": {
      "promotion": "offer",
      "advertisement": "offer",
      "product_launch": "minimal",
      "feature_release": "minimal",
      "case_study": "minimal",
      "announcement": "brand",
      "thought_leadership": "minimal",
      "event": "minimal",
      "webinar": "minimal",
      "hiring": "minimal"
    },
    "color": {
      "promotion": "warm",
      "advertisement": "bold",
      "product_launch": "enterprise",
      "feature_release": "cool",
      "case_study": "enterprise",
      "announcement": "neutral",
      "thought_leadership": "neutral",
      "event": "cool",
      "webinar": "cool",
      "hiring": "warm",
      "enterprise_saas": "enterprise"
    }
  }
} as const;
