import type { ComponentType } from "react";
import type { UiPatternProps } from "./UiPatterns";
import {
  DashboardMetricsPattern,
  FeatureListPattern,
  KanbanBoardPattern,
  MetricCardsRowPattern,
  NotificationStackPattern,
  PricingCardPattern,
  ProductFramePattern,
  ProgressRingPattern,
  QuoteHighlightPattern,
  StatHighlightPattern,
  TablePreviewPattern,
  TestimonialCardPattern,
} from "./UiPatterns";
import {
  AvatarStackPattern,
  BenefitPillsPattern,
  CalendarPreviewPattern,
  CaseStudyCardPattern,
  ChatThreadPattern,
  ChecklistBenefitsPattern,
  CompetitorRowPattern,
  CrmListPattern,
  CtaBannerPattern,
  DiscountStripPattern,
  DualPricingPattern,
  FormCardPattern,
  GrowthBadgePattern,
  IconBenefitRowPattern,
  InboxPreviewPattern,
  KpiHeroPattern,
  LogoWallPattern,
  NumberedStepsPattern,
  OfferBadgeCardPattern,
  PercentSplitPattern,
  ProcessCardsPattern,
  RevenueStatPattern,
  RoadmapStripPattern,
  RoiCalloutPattern,
  StarReviewPattern,
  SwitchReasonPattern,
  TrustBadgesPattern,
  ValuePropCardPattern,
  VsSplitCardPattern,
} from "./UiPatternsExtra";

export const UI_PATTERN_COMPONENTS: Record<string, ComponentType<UiPatternProps>> = {
  "stat-highlight": StatHighlightPattern,
  "feature-list": FeatureListPattern,
  "pricing-card": PricingCardPattern,
  "testimonial-card": TestimonialCardPattern,
  "kanban-board": KanbanBoardPattern,
  "dashboard-metrics": DashboardMetricsPattern,
  "notification-stack": NotificationStackPattern,
  "progress-ring": ProgressRingPattern,
  "table-preview": TablePreviewPattern,
  "metric-cards-row": MetricCardsRowPattern,
  "quote-highlight": QuoteHighlightPattern,
  "product-frame": ProductFramePattern,
  "kpi-hero": KpiHeroPattern,
  "growth-badge": GrowthBadgePattern,
  "revenue-stat": RevenueStatPattern,
  "roi-callout": RoiCalloutPattern,
  "percent-split": PercentSplitPattern,
  "logo-wall": LogoWallPattern,
  "star-review": StarReviewPattern,
  "case-study-card": CaseStudyCardPattern,
  "trust-badges": TrustBadgesPattern,
  "avatar-stack": AvatarStackPattern,
  "vs-split-card": VsSplitCardPattern,
  "competitor-row": CompetitorRowPattern,
  "switch-reason": SwitchReasonPattern,
  "checklist-benefits": ChecklistBenefitsPattern,
  "icon-benefit-row": IconBenefitRowPattern,
  "benefit-pills": BenefitPillsPattern,
  "dual-pricing": DualPricingPattern,
  "offer-badge-card": OfferBadgeCardPattern,
  "discount-strip": DiscountStripPattern,
  "numbered-steps": NumberedStepsPattern,
  "process-cards": ProcessCardsPattern,
  "roadmap-strip": RoadmapStripPattern,
  "calendar-preview": CalendarPreviewPattern,
  "chat-thread": ChatThreadPattern,
  "form-card": FormCardPattern,
  "crm-list": CrmListPattern,
  "inbox-preview": InboxPreviewPattern,
  "cta-banner": CtaBannerPattern,
  "value-prop-card": ValuePropCardPattern,
};

export function getUiPatternComponent(
  libraryId?: string | null,
): ComponentType<UiPatternProps> | null {
  if (!libraryId) return null;
  return UI_PATTERN_COMPONENTS[libraryId] ?? null;
}
